/* Generated by Yosys 0.25+83 (git sha1 755b753e1, aarch64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

/* top =  1  */
/* src = "d14_jessief_trafficlight/src/toplevel_chip.v:4.1-18.10" */
module d14_jessief_trafficlight(io_in, io_out);
  wire [10:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  /* force_downto = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:15.12-15.20|d14_jessief_trafficlight/src/chip.sv:32.11-32.94|/Users/anish/workspace/oss-cad-suite/libexec/../share/yosys/techmap.v:270.23-270.24" */
  wire [7:0] _138_;
  /* force_downto = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:15.12-15.20|d14_jessief_trafficlight/src/chip.sv:31.11-31.93|/Users/anish/workspace/oss-cad-suite/libexec/../share/yosys/techmap.v:270.23-270.24" */
  wire [7:0] _139_;
  /* force_downto = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:15.12-15.20|d14_jessief_trafficlight/src/chip.sv:30.11-30.102|/Users/anish/workspace/oss-cad-suite/libexec/../share/yosys/techmap.v:270.23-270.24" */
  wire [7:0] _140_;
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:5.18-5.23" */
  input [13:0] io_in;
  wire [13:0] io_in;
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:6.19-6.25" */
  output [13:0] io_out;
  wire [13:0] io_out;
  /* hdlname = "mchip button" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:21.17-21.23" */
  wire \mchip.button ;
  /* hdlname = "mchip car1" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:8.7-8.11" */
  wire \mchip.car1 ;
  /* hdlname = "mchip car2" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:8.13-8.17" */
  wire \mchip.car2 ;
  /* hdlname = "mchip car3" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:8.19-8.23" */
  wire \mchip.car3 ;
  /* hdlname = "mchip car4" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:8.25-8.29" */
  wire \mchip.car4 ;
  /* hdlname = "mchip clock" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:5.15-5.20" */
  wire \mchip.clock ;
  /* hdlname = "mchip control car1" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:49.17-49.21|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.car1 ;
  /* hdlname = "mchip control car2" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:49.23-49.27|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.car2 ;
  /* hdlname = "mchip control car3" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:49.29-49.33|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.car3 ;
  /* hdlname = "mchip control car4" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:49.35-49.39|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.car4 ;
  /* hdlname = "mchip control clock" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:48.17-48.22|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.clock ;
  /* hdlname = "mchip control five_clr" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:60.17-60.25|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  reg \mchip.control.five_clr ;
  /* hdlname = "mchip control five_en" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:59.17-59.24|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  reg \mchip.control.five_en ;
  /* hdlname = "mchip control green1" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:51.32-51.38|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.green1 ;
  /* hdlname = "mchip control green2" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:52.32-52.38|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.green2 ;
  /* hdlname = "mchip control green3" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:53.32-53.38|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.green3 ;
  /* enum_type = "$enum0" */
  /* hdlname = "mchip control nextState" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:64.62-64.71|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire [3:0] \mchip.control.nextState ;
  /* hdlname = "mchip control orange" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:54.23-54.29|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.orange ;
  /* hdlname = "mchip control ped" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:49.41-49.44|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.ped ;
  /* hdlname = "mchip control ped_clr" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:61.17-61.24|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  reg \mchip.control.ped_clr ;
  /* hdlname = "mchip control red1" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:51.17-51.21|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.red1 ;
  /* hdlname = "mchip control red2" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:52.17-52.21|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.red2 ;
  /* hdlname = "mchip control red3" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:53.17-53.21|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.red3 ;
  /* hdlname = "mchip control reset" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:48.24-48.29|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.reset ;
  /* enum_type = "$enum0" */
  /* hdlname = "mchip control state" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:64.55-64.60|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  reg [3:0] \mchip.control.state ;
  /* hdlname = "mchip control stop_clr" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:58.17-58.25|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  reg \mchip.control.stop_clr ;
  /* hdlname = "mchip control stop_en" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:57.17-57.24|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  reg \mchip.control.stop_en ;
  /* hdlname = "mchip control stop_five" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:50.40-50.49|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.stop_five ;
  /* hdlname = "mchip control stop_ped" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:50.30-50.38|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.stop_ped ;
  /* hdlname = "mchip control stop_yellow" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:50.17-50.28|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.stop_yellow ;
  /* hdlname = "mchip control turn" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:54.17-54.21|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.turn ;
  /* hdlname = "mchip control white" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:54.31-54.36|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.white ;
  /* hdlname = "mchip control yellow1" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:51.23-51.30|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.yellow1 ;
  /* hdlname = "mchip control yellow2" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:52.23-52.30|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.yellow2 ;
  /* hdlname = "mchip control yellow3" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:53.23-53.30|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  wire \mchip.control.yellow3 ;
  /* hdlname = "mchip control yellow_clr" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:56.17-56.27|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  reg \mchip.control.yellow_clr ;
  /* hdlname = "mchip control yellow_en" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:55.17-55.26|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  reg \mchip.control.yellow_en ;
  /* hdlname = "mchip five D" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:5.31-5.32|d14_jessief_trafficlight/src/chip.sv:32.11-32.94" */
  wire [7:0] \mchip.five.D ;
  /* hdlname = "mchip five Q" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:7.31-7.32|d14_jessief_trafficlight/src/chip.sv:32.11-32.94" */
  wire [7:0] \mchip.five.Q ;
  /* hdlname = "mchip five clear" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.31-6.36|d14_jessief_trafficlight/src/chip.sv:32.11-32.94" */
  wire \mchip.five.clear ;
  /* hdlname = "mchip five clock" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.44-6.49|d14_jessief_trafficlight/src/chip.sv:32.11-32.94" */
  wire \mchip.five.clock ;
  /* hdlname = "mchip five en" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.51-6.53|d14_jessief_trafficlight/src/chip.sv:32.11-32.94" */
  wire \mchip.five.en ;
  /* hdlname = "mchip five load" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.38-6.42|d14_jessief_trafficlight/src/chip.sv:32.11-32.94" */
  wire \mchip.five.load ;
  /* hdlname = "mchip five_clr" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:19.17-19.25" */
  wire \mchip.five_clr ;
  /* hdlname = "mchip five_en" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:18.17-18.24" */
  wire \mchip.five_en ;
  /* hdlname = "mchip green1" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:10.32-10.38" */
  wire \mchip.green1 ;
  /* hdlname = "mchip green2" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:11.32-11.38" */
  wire \mchip.green2 ;
  /* hdlname = "mchip green3" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:12.32-12.38" */
  wire \mchip.green3 ;
  /* hdlname = "mchip io_in" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:4.22-4.27" */
  /* unused_bits = "5 6 7 8 9 10 11" */
  wire [11:0] \mchip.io_in ;
  /* hdlname = "mchip io_out" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:6.23-6.29" */
  wire [11:0] \mchip.io_out ;
  /* hdlname = "mchip orange" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:13.23-13.29" */
  wire \mchip.orange ;
  /* hdlname = "mchip ped" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:8.31-8.34" */
  wire \mchip.ped ;
  /* hdlname = "mchip ped_clr" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:20.17-20.24" */
  wire \mchip.ped_clr ;
  /* hdlname = "mchip pedestrian button" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:34.16-34.22|d14_jessief_trafficlight/src/chip.sv:33.12-33.56" */
  wire \mchip.pedestrian.button ;
  /* hdlname = "mchip pedestrian clock" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:34.33-34.38|d14_jessief_trafficlight/src/chip.sv:33.12-33.56" */
  wire \mchip.pedestrian.clock ;
  /* hdlname = "mchip pedestrian ped" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:35.17-35.20|d14_jessief_trafficlight/src/chip.sv:33.12-33.56" */
  reg \mchip.pedestrian.ped ;
  /* hdlname = "mchip pedestrian ped_clr" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:34.24-34.31|d14_jessief_trafficlight/src/chip.sv:33.12-33.56" */
  wire \mchip.pedestrian.ped_clr ;
  /* hdlname = "mchip red1" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:10.17-10.21" */
  wire \mchip.red1 ;
  /* hdlname = "mchip red2" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:11.17-11.21" */
  wire \mchip.red2 ;
  /* hdlname = "mchip red3" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:12.17-12.21" */
  wire \mchip.red3 ;
  /* hdlname = "mchip reset" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:5.22-5.27" */
  wire \mchip.reset ;
  /* hdlname = "mchip stop D" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:5.31-5.32|d14_jessief_trafficlight/src/chip.sv:31.11-31.93" */
  wire [7:0] \mchip.stop.D ;
  /* hdlname = "mchip stop Q" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:7.31-7.32|d14_jessief_trafficlight/src/chip.sv:31.11-31.93" */
  wire [7:0] \mchip.stop.Q ;
  /* hdlname = "mchip stop clear" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.31-6.36|d14_jessief_trafficlight/src/chip.sv:31.11-31.93" */
  wire \mchip.stop.clear ;
  /* hdlname = "mchip stop clock" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.44-6.49|d14_jessief_trafficlight/src/chip.sv:31.11-31.93" */
  wire \mchip.stop.clock ;
  /* hdlname = "mchip stop en" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.51-6.53|d14_jessief_trafficlight/src/chip.sv:31.11-31.93" */
  wire \mchip.stop.en ;
  /* hdlname = "mchip stop load" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.38-6.42|d14_jessief_trafficlight/src/chip.sv:31.11-31.93" */
  wire \mchip.stop.load ;
  /* hdlname = "mchip stop_clr" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:17.17-17.25" */
  wire \mchip.stop_clr ;
  /* hdlname = "mchip stop_en" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:16.17-16.24" */
  wire \mchip.stop_en ;
  /* hdlname = "mchip stop_five" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:9.40-9.49" */
  wire \mchip.stop_five ;
  /* hdlname = "mchip stop_ped" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:9.30-9.38" */
  wire \mchip.stop_ped ;
  /* hdlname = "mchip stop_yellow" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:9.17-9.28" */
  wire \mchip.stop_yellow ;
  /* hdlname = "mchip turn" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:13.17-13.21" */
  wire \mchip.turn ;
  /* hdlname = "mchip white" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:13.31-13.36" */
  wire \mchip.white ;
  /* hdlname = "mchip yellow D" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:5.31-5.32|d14_jessief_trafficlight/src/chip.sv:30.11-30.102" */
  wire [7:0] \mchip.yellow.D ;
  /* hdlname = "mchip yellow Q" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:7.31-7.32|d14_jessief_trafficlight/src/chip.sv:30.11-30.102" */
  wire [7:0] \mchip.yellow.Q ;
  /* hdlname = "mchip yellow clear" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.31-6.36|d14_jessief_trafficlight/src/chip.sv:30.11-30.102" */
  wire \mchip.yellow.clear ;
  /* hdlname = "mchip yellow clock" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.44-6.49|d14_jessief_trafficlight/src/chip.sv:30.11-30.102" */
  wire \mchip.yellow.clock ;
  /* hdlname = "mchip yellow en" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.51-6.53|d14_jessief_trafficlight/src/chip.sv:30.11-30.102" */
  wire \mchip.yellow.en ;
  /* hdlname = "mchip yellow load" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:6.38-6.42|d14_jessief_trafficlight/src/chip.sv:30.11-30.102" */
  wire \mchip.yellow.load ;
  /* hdlname = "mchip yellow1" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:10.23-10.30" */
  wire \mchip.yellow1 ;
  /* hdlname = "mchip yellow2" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:11.23-11.30" */
  wire \mchip.yellow2 ;
  /* hdlname = "mchip yellow3" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:12.23-12.30" */
  wire \mchip.yellow3 ;
  /* hdlname = "mchip yellow_clr" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:15.17-15.27" */
  wire \mchip.yellow_clr ;
  /* hdlname = "mchip yellow_en" */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/chip.sv:14.17-14.26" */
  wire \mchip.yellow_en ;
  assign _138_[0] = ~\mchip.five.Q [0];
  assign _139_[0] = ~\mchip.stop.Q [0];
  assign _083_ = \mchip.control.state [3] & ~(\mchip.control.state [2]);
  assign _084_ = \mchip.control.state [1] | \mchip.control.state [0];
  assign _085_ = _083_ & ~(_084_);
  assign _086_ = \mchip.control.state [2] & ~(\mchip.control.state [3]);
  assign _087_ = \mchip.control.state [1] & \mchip.control.state [0];
  assign _088_ = _087_ & _086_;
  assign _089_ = ~(_088_ | _085_);
  assign _090_ = \mchip.control.state [1] | ~(\mchip.control.state [0]);
  assign _091_ = _086_ & ~(_090_);
  assign _092_ = \mchip.control.state [0] | ~(\mchip.control.state [1]);
  assign _093_ = _086_ & ~(_092_);
  assign _094_ = _093_ | _091_;
  assign _095_ = _089_ & ~(_094_);
  assign _096_ = \mchip.control.state [3] | \mchip.control.state [2];
  assign _097_ = ~(_096_ | _090_);
  assign _098_ = _096_ | _092_;
  assign _099_ = _097_ | ~(_098_);
  assign _100_ = _087_ & ~(_096_);
  assign _101_ = _086_ & ~(_084_);
  assign _102_ = _101_ | _100_;
  assign _103_ = _102_ | _099_;
  assign _104_ = _095_ & ~(_103_);
  assign _105_ = ~(_101_ & \mchip.stop.Q [0]);
  assign _106_ = _085_ & ~(\mchip.five.Q [0]);
  assign _107_ = _105_ & ~(_106_);
  assign \mchip.control.nextState [3] = ~(_107_ | _104_);
  assign _000_[10] = \mchip.control.nextState [3] & ~(io_in[13]);
  assign _140_[0] = ~\mchip.yellow.Q [0];
  assign _108_ = ~io_in[4];
  assign _109_ = ~io_in[3];
  assign _110_ = _109_ & ~(_098_);
  assign _111_ = io_in[2] | io_in[1];
  assign _112_ = _100_ & ~(_111_);
  assign _113_ = _112_ | _110_;
  assign _114_ = _098_ & ~(_100_);
  assign _115_ = _114_ ? _108_ : _113_;
  assign _116_ = _139_[0] & ~(_115_);
  assign _117_ = _116_ | ~(_097_);
  assign _118_ = ~(_116_ | _098_);
  assign _119_ = _117_ & ~(_118_);
  assign _120_ = _100_ & ~(_116_);
  assign _121_ = _101_ & ~(\mchip.stop.Q [0]);
  assign _122_ = _121_ | _120_;
  assign _123_ = _119_ & ~(_122_);
  assign _124_ = _109_ & ~(_111_);
  assign _125_ = _124_ & ~(io_in[4]);
  assign _126_ = ~(_125_ & \mchip.five.Q [0]);
  assign _127_ = _085_ & ~(_126_);
  assign _128_ = _125_ | \mchip.pedestrian.ped ;
  assign _129_ = \mchip.yellow.Q [0] & ~(_128_);
  assign _130_ = _088_ & ~(_129_);
  assign _131_ = _130_ | _127_;
  assign _132_ = io_in[4] & ~(\mchip.pedestrian.ped );
  assign _133_ = ~(_132_ | _111_);
  assign _134_ = _133_ & ~(io_in[3]);
  assign _135_ = \mchip.yellow.Q [0] & ~(_134_);
  assign _136_ = _091_ & ~(_135_);
  assign _137_ = ~(io_in[2] | io_in[1]);
  assign _019_ = ~\mchip.pedestrian.ped ;
  assign _020_ = ~(io_in[4] | io_in[3]);
  assign _021_ = _019_ & ~(_020_);
  assign _022_ = _137_ & ~(_021_);
  assign _023_ = \mchip.yellow.Q [0] & ~(_022_);
  assign _024_ = _093_ & ~(_023_);
  assign _025_ = _024_ | _136_;
  assign _026_ = _025_ | _131_;
  assign _027_ = _026_ | ~(_123_);
  assign _028_ = _111_ | _019_;
  assign _029_ = _028_ | io_in[3];
  assign _030_ = _108_ & ~(_029_);
  assign \mchip.control.nextState [2] = _104_ ? _030_ : _027_;
  assign _031_ = \mchip.control.nextState [2] & ~(io_in[13]);
  assign _032_ = ~io_in[13];
  assign _033_ = _124_ | io_in[4];
  assign _034_ = _033_ | _138_[0];
  assign _035_ = _085_ & ~(_034_);
  assign _036_ = _019_ & ~(_033_);
  assign _037_ = \mchip.yellow.Q [0] & ~(_036_);
  assign _038_ = _088_ & ~(_037_);
  assign _039_ = _038_ | _035_;
  assign _040_ = _124_ | _140_[0];
  assign _041_ = _091_ & ~(_040_);
  assign _042_ = io_in[4] | ~(io_in[3]);
  assign _043_ = _019_ & ~(_042_);
  assign _044_ = _043_ | _111_;
  assign _045_ = \mchip.yellow.Q [0] & ~(_044_);
  assign _046_ = _093_ & ~(_045_);
  assign _047_ = _046_ | _041_;
  assign _048_ = _047_ | _039_;
  assign _049_ = _114_ & ~(_048_);
  assign _050_ = _104_ ? _033_ : _049_;
  assign _051_ = _032_ & ~(_050_);
  assign _052_ = _051_ | _031_;
  assign _004_ = _052_ | _000_[10];
  assign _053_ = _051_ | _000_[10];
  assign _003_ = _053_ | ~(_031_);
  assign _006_ = _031_ | _000_[10];
  assign _007_ = _050_ | io_in[13];
  assign _002_ = _006_ | _007_;
  assign _005_ = _000_[10] | ~(_031_);
  assign _001_ = _005_ | _007_;
  assign _054_ = _109_ & ~(_137_);
  assign _055_ = _108_ & ~(_054_);
  assign _056_ = _055_ | _138_[0];
  assign _057_ = _056_ | ~(_085_);
  assign _058_ = _019_ & ~(_055_);
  assign _059_ = \mchip.yellow.Q [0] & ~(_058_);
  assign _060_ = _088_ & ~(_059_);
  assign _061_ = _057_ & ~(_060_);
  assign _062_ = _109_ & ~(_133_);
  assign _063_ = \mchip.yellow.Q [0] & ~(_062_);
  assign _064_ = _091_ & ~(_063_);
  assign _065_ = _133_ | _140_[0];
  assign _066_ = _093_ & ~(_065_);
  assign _067_ = _066_ | _064_;
  assign _068_ = _061_ & ~(_067_);
  assign _069_ = _100_ | _097_;
  assign _070_ = _068_ & ~(_069_);
  assign _071_ = _104_ ? _055_ : _070_;
  assign \mchip.control.nextState [0] = ~_071_;
  assign \mchip.control.nextState [1] = ~_050_;
  assign _008_ = _032_ & ~(_071_);
  assign _017_ = _008_ | _051_;
  assign _016_ = _007_ & ~(_008_);
  assign _015_ = _017_ ^ _031_;
  assign _018_ = ~_008_;
  assign _072_ = _031_ & ~(_017_);
  assign _073_ = _008_ & ~(_051_);
  assign _074_ = ~(_073_ | _031_);
  assign _009_ = _074_ | _072_;
  assign _010_ = _016_ ^ _031_;
  assign _075_ = _031_ & ~(_073_);
  assign _011_ = _075_ | _074_;
  assign _076_ = _051_ & ~(_008_);
  assign _077_ = _031_ & ~(_076_);
  assign _078_ = ~(_076_ | _031_);
  assign _012_ = _078_ | _077_;
  assign _079_ = _017_ & ~(_076_);
  assign _080_ = _031_ & ~(_079_);
  assign _081_ = ~(_079_ | _031_);
  assign _013_ = _081_ | _080_;
  assign _082_ = _016_ & ~(_031_);
  assign _014_ = _082_ | _072_;
  /* \always_ff  = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:66.3-70.26|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.control.state [0] <= 1'h0;
    else \mchip.control.state [0] <= \mchip.control.nextState [0];
  /* \always_ff  = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:66.3-70.26|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.control.state [1] <= 1'h0;
    else \mchip.control.state [1] <= \mchip.control.nextState [1];
  /* \always_ff  = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:66.3-70.26|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.control.state [2] <= 1'h0;
    else \mchip.control.state [2] <= \mchip.control.nextState [2];
  /* \always_ff  = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:66.3-70.26|d14_jessief_trafficlight/src/chip.sv:34.7-34.18" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.control.state [3] <= 1'h0;
    else \mchip.control.state [3] <= \mchip.control.nextState [3];
  reg \io_out_reg[3] ;
  always @(posedge io_in[12])
    if (_006_) \io_out_reg[3]  <= 1'h0;
    else \io_out_reg[3]  <= _008_;
  assign io_out[3] = \io_out_reg[3] ;
  always @(posedge io_in[12])
    if (_006_) \mchip.control.five_clr  <= 1'h0;
    else \mchip.control.five_clr  <= _007_;
  reg \io_out_reg[7] ;
  always @(posedge io_in[12])
    if (_001_) \io_out_reg[7]  <= 1'h0;
    else \io_out_reg[7]  <= _018_;
  assign io_out[7] = \io_out_reg[7] ;
  always @(posedge io_in[12])
    \mchip.control.five_en  <= _000_[10];
  reg \io_out_reg[4] ;
  always @(posedge io_in[12])
    if (_005_) \io_out_reg[4]  <= 1'h0;
    else \io_out_reg[4]  <= _008_;
  assign io_out[4] = \io_out_reg[4] ;
  reg \io_out_reg[0] ;
  always @(posedge io_in[12])
    if (_005_) \io_out_reg[0]  <= 1'h0;
    else \io_out_reg[0]  <= _016_;
  assign io_out[0] = \io_out_reg[0] ;
  always @(posedge io_in[12])
    if (_005_) \mchip.control.yellow_en  <= 1'h0;
    else \mchip.control.yellow_en  <= _017_;
  reg \io_out_reg[1] ;
  always @(posedge io_in[12])
    if (_005_) \io_out_reg[1]  <= 1'h1;
    else \io_out_reg[1]  <= _017_;
  assign io_out[1] = \io_out_reg[1] ;
  reg \io_out_reg[9] ;
  always @(posedge io_in[12])
    if (_004_) \io_out_reg[9]  <= 1'h0;
    else \io_out_reg[9]  <= _008_;
  assign io_out[9] = \io_out_reg[9] ;
  always @(posedge io_in[12])
    if (_000_[10]) \mchip.control.stop_en  <= 1'h0;
    else \mchip.control.stop_en  <= _015_;
  always @(posedge io_in[12])
    if (_000_[10]) \mchip.control.yellow_clr  <= 1'h0;
    else \mchip.control.yellow_clr  <= _009_;
  always @(posedge io_in[12])
    if (_000_[10]) \mchip.control.stop_clr  <= 1'h1;
    else \mchip.control.stop_clr  <= _010_;
  reg \io_out_reg[11] ;
  always @(posedge io_in[12])
    if (_000_[10]) \io_out_reg[11]  <= 1'h1;
    else \io_out_reg[11]  <= _011_;
  assign io_out[11] = \io_out_reg[11] ;
  reg \io_out_reg[8] ;
  always @(posedge io_in[12])
    if (_000_[10]) \io_out_reg[8]  <= 1'h1;
    else \io_out_reg[8]  <= _012_;
  assign io_out[8] = \io_out_reg[8] ;
  reg \io_out_reg[5] ;
  always @(posedge io_in[12])
    if (_000_[10]) \io_out_reg[5]  <= 1'h1;
    else \io_out_reg[5]  <= _013_;
  assign io_out[5] = \io_out_reg[5] ;
  always @(posedge io_in[12])
    if (_000_[10]) \mchip.control.ped_clr  <= 1'h0;
    else \mchip.control.ped_clr  <= _014_;
  reg \io_out_reg[10] ;
  always @(posedge io_in[12])
    if (_003_) \io_out_reg[10]  <= 1'h0;
    else \io_out_reg[10]  <= _008_;
  assign io_out[10] = \io_out_reg[10] ;
  reg \io_out_reg[6] ;
  always @(posedge io_in[12])
    if (_002_) \io_out_reg[6]  <= 1'h0;
    else \io_out_reg[6]  <= _018_;
  assign io_out[6] = \io_out_reg[6] ;
  reg \io_out_reg[2] ;
  always @(posedge io_in[12])
    if (_002_) \io_out_reg[2]  <= 1'h0;
    else \io_out_reg[2]  <= _008_;
  assign io_out[2] = \io_out_reg[2] ;
  /* \always_ff  = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:37.3-43.18|d14_jessief_trafficlight/src/chip.sv:33.12-33.56" */
  always @(posedge io_in[12])
    if (io_in[0]) \mchip.pedestrian.ped  <= 1'h1;
    else if (\mchip.control.ped_clr ) \mchip.pedestrian.ped  <= 1'h0;
  reg \mchip.five.Q_reg[0] ;
  /* \always_ff  = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:9.3-17.14|d14_jessief_trafficlight/src/chip.sv:32.11-32.94" */
  always @(posedge io_in[12])
    if (\mchip.control.five_clr ) \mchip.five.Q_reg[0]  <= 1'h0;
    else if (\mchip.control.five_en ) \mchip.five.Q_reg[0]  <= _138_[0];
  assign \mchip.five.Q [0] = \mchip.five.Q_reg[0] ;
  reg \mchip.stop.Q_reg[0] ;
  /* \always_ff  = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:9.3-17.14|d14_jessief_trafficlight/src/chip.sv:31.11-31.93" */
  always @(posedge io_in[12])
    if (\mchip.control.stop_clr ) \mchip.stop.Q_reg[0]  <= 1'h0;
    else if (\mchip.control.stop_en ) \mchip.stop.Q_reg[0]  <= _139_[0];
  assign \mchip.stop.Q [0] = \mchip.stop.Q_reg[0] ;
  reg \mchip.yellow.Q_reg[0] ;
  /* \always_ff  = 32'd1 */
  /* src = "d14_jessief_trafficlight/src/toplevel_chip.v:9.13-14.6|d14_jessief_trafficlight/src/FSMD.sv:9.3-17.14|d14_jessief_trafficlight/src/chip.sv:30.11-30.102" */
  always @(posedge io_in[12])
    if (\mchip.control.yellow_clr ) \mchip.yellow.Q_reg[0]  <= 1'h0;
    else if (\mchip.control.yellow_en ) \mchip.yellow.Q_reg[0]  <= _140_[0];
  assign \mchip.yellow.Q [0] = \mchip.yellow.Q_reg[0] ;
  assign _000_[9:0] = 10'h000;
  assign _138_[7:1] = 7'h00;
  assign _139_[7:1] = 7'h00;
  assign _140_[7:1] = 7'h00;
  assign io_out[13:12] = 2'h0;
  assign \mchip.button  = io_in[0];
  assign \mchip.car1  = io_in[4];
  assign \mchip.car2  = io_in[3];
  assign \mchip.car3  = io_in[2];
  assign \mchip.car4  = io_in[1];
  assign \mchip.clock  = io_in[12];
  assign \mchip.control.car1  = io_in[4];
  assign \mchip.control.car2  = io_in[3];
  assign \mchip.control.car3  = io_in[2];
  assign \mchip.control.car4  = io_in[1];
  assign \mchip.control.clock  = io_in[12];
  assign \mchip.control.green1  = io_out[9];
  assign \mchip.control.green2  = io_out[6];
  assign \mchip.control.green3  = io_out[3];
  assign \mchip.control.orange  = io_out[1];
  assign \mchip.control.ped  = \mchip.pedestrian.ped ;
  assign \mchip.control.red1  = io_out[11];
  assign \mchip.control.red2  = io_out[8];
  assign \mchip.control.red3  = io_out[5];
  assign \mchip.control.reset  = io_in[13];
  assign \mchip.control.stop_five  = \mchip.five.Q [0];
  assign \mchip.control.stop_ped  = \mchip.stop.Q [0];
  assign \mchip.control.stop_yellow  = \mchip.yellow.Q [0];
  assign \mchip.control.turn  = io_out[2];
  assign \mchip.control.white  = io_out[0];
  assign \mchip.control.yellow1  = io_out[10];
  assign \mchip.control.yellow2  = io_out[7];
  assign \mchip.control.yellow3  = io_out[4];
  assign \mchip.five.D  = 8'h00;
  assign \mchip.five.Q [7:1] = 7'h00;
  assign \mchip.five.clear  = \mchip.control.five_clr ;
  assign \mchip.five.clock  = io_in[12];
  assign \mchip.five.en  = \mchip.control.five_en ;
  assign \mchip.five.load  = 1'h0;
  assign \mchip.five_clr  = \mchip.control.five_clr ;
  assign \mchip.five_en  = \mchip.control.five_en ;
  assign \mchip.green1  = io_out[9];
  assign \mchip.green2  = io_out[6];
  assign \mchip.green3  = io_out[3];
  assign \mchip.io_in  = io_in[11:0];
  assign \mchip.io_out  = io_out[11:0];
  assign \mchip.orange  = io_out[1];
  assign \mchip.ped  = \mchip.pedestrian.ped ;
  assign \mchip.ped_clr  = \mchip.control.ped_clr ;
  assign \mchip.pedestrian.button  = io_in[0];
  assign \mchip.pedestrian.clock  = io_in[12];
  assign \mchip.pedestrian.ped_clr  = \mchip.control.ped_clr ;
  assign \mchip.red1  = io_out[11];
  assign \mchip.red2  = io_out[8];
  assign \mchip.red3  = io_out[5];
  assign \mchip.reset  = io_in[13];
  assign \mchip.stop.D  = 8'h00;
  assign \mchip.stop.Q [7:1] = 7'h00;
  assign \mchip.stop.clear  = \mchip.control.stop_clr ;
  assign \mchip.stop.clock  = io_in[12];
  assign \mchip.stop.en  = \mchip.control.stop_en ;
  assign \mchip.stop.load  = 1'h0;
  assign \mchip.stop_clr  = \mchip.control.stop_clr ;
  assign \mchip.stop_en  = \mchip.control.stop_en ;
  assign \mchip.stop_five  = \mchip.five.Q [0];
  assign \mchip.stop_ped  = \mchip.stop.Q [0];
  assign \mchip.stop_yellow  = \mchip.yellow.Q [0];
  assign \mchip.turn  = io_out[2];
  assign \mchip.white  = io_out[0];
  assign \mchip.yellow.D  = 8'h00;
  assign \mchip.yellow.Q [7:1] = 7'h00;
  assign \mchip.yellow.clear  = \mchip.control.yellow_clr ;
  assign \mchip.yellow.clock  = io_in[12];
  assign \mchip.yellow.en  = \mchip.control.yellow_en ;
  assign \mchip.yellow.load  = 1'h0;
  assign \mchip.yellow1  = io_out[10];
  assign \mchip.yellow2  = io_out[7];
  assign \mchip.yellow3  = io_out[4];
  assign \mchip.yellow_clr  = \mchip.control.yellow_clr ;
  assign \mchip.yellow_en  = \mchip.control.yellow_en ;
endmodule
