`default_nettype none

// DO NOT EDIT THIS FILE
module toplevel_chip (
    input [13:0] io_in,
    output [13:0] io_out
);

    my_chip mchip (
        .io_in(io_in[11:0]),
        .io_out(io_out[11:0]),
        .clock(io_in[12]),
        .reset(io_in[13])
    );

    assign io_out[13:12] = 2'b00;

endmodule
