/* Generated by Yosys 0.25+83 (git sha1 755b753e1, aarch64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

/* top =  1  */
/* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:4.1-18.10" */
module d24_mnguyen2_tpu(io_in, io_out);
  wire _000_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _001_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _002_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _003_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _004_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _005_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _006_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _007_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _008_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _009_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _010_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _011_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _012_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _013_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _014_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _015_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:0.0-0.0|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:5.18-5.23" */
  input [13:0] io_in;
  wire [13:0] io_in;
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:6.19-6.25" */
  output [13:0] io_out;
  wire [13:0] io_out;
  /* hdlname = "mchip TPU KERNAL_MAT D" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:8.55-8.56|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* unused_bits = "1 2 3 4 5 6 7" */
  /* wiretype = "\\data_t" */
  wire [7:0] \mchip.TPU.KERNAL_MAT.D ;
  /* hdlname = "mchip TPU KERNAL_MAT Q" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:10.17-10.18|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* wiretype = "\\data_t" */
  wire [7:0] \mchip.TPU.KERNAL_MAT.Q ;
  /* hdlname = "mchip TPU KERNAL_MAT clk" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:7.55-7.58|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.KERNAL_MAT.clk ;
  /* hdlname = "mchip TPU KERNAL_MAT data" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:12.23-12.27|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* wiretype = "\\data_t" */
  reg [7:0] \mchip.TPU.KERNAL_MAT.data ;
  /* hdlname = "mchip TPU KERNAL_MAT rst" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:7.60-7.63|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.KERNAL_MAT.rst ;
  /* hdlname = "mchip TPU KERNAL_MAT we" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:7.65-7.67|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.KERNAL_MAT.we ;
  /* hdlname = "mchip TPU MATRIX_MAT D" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:8.55-8.56|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* unused_bits = "1 2 3 4 5 6 7" */
  /* wiretype = "\\data_t" */
  wire [7:0] \mchip.TPU.MATRIX_MAT.D ;
  /* hdlname = "mchip TPU MATRIX_MAT Q" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:10.17-10.18|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* wiretype = "\\data_t" */
  wire [7:0] \mchip.TPU.MATRIX_MAT.Q ;
  /* hdlname = "mchip TPU MATRIX_MAT clk" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:7.55-7.58|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.MATRIX_MAT.clk ;
  /* hdlname = "mchip TPU MATRIX_MAT data" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:12.23-12.27|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* wiretype = "\\data_t" */
  reg [7:0] \mchip.TPU.MATRIX_MAT.data ;
  /* hdlname = "mchip TPU MATRIX_MAT rst" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:7.60-7.63|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.MATRIX_MAT.rst ;
  /* hdlname = "mchip TPU MATRIX_MAT we" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:7.65-7.67|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.MATRIX_MAT.we ;
  /* hdlname = "mchip TPU base_addr" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:59.16-59.25|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* wiretype = "\\base_coord_t" */
  wire [9:0] \mchip.TPU.base_addr ;
  /* hdlname = "mchip TPU base_addr_x_counter Q" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:7.33-7.34|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  reg [9:0] \mchip.TPU.base_addr_x_counter.Q ;
  /* hdlname = "mchip TPU base_addr_x_counter Q_next" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:9.26-9.32|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire [9:0] \mchip.TPU.base_addr_x_counter.Q_next ;
  /* hdlname = "mchip TPU base_addr_x_counter clk" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:6.16-6.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.base_addr_x_counter.clk ;
  /* hdlname = "mchip TPU base_addr_x_counter rst" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:6.21-6.24|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.base_addr_x_counter.rst ;
  /* hdlname = "mchip TPU base_addr_y_counter Q" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:7.33-7.34|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  reg [9:0] \mchip.TPU.base_addr_y_counter.Q ;
  /* hdlname = "mchip TPU base_addr_y_counter Q_next" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:9.26-9.32|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire [9:0] \mchip.TPU.base_addr_y_counter.Q_next ;
  /* hdlname = "mchip TPU base_addr_y_counter clk" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:6.16-6.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.base_addr_y_counter.clk ;
  /* hdlname = "mchip TPU base_addr_y_counter rst" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:6.21-6.24|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.base_addr_y_counter.rst ;
  /* hdlname = "mchip TPU clk" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:7.16-7.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.clk ;
  /* hdlname = "mchip TPU conv_mac a" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/mac.sv:6.58-6.59|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire [7:0] \mchip.TPU.conv_mac.a ;
  /* hdlname = "mchip TPU conv_mac b" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/mac.sv:6.61-6.62|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire [7:0] \mchip.TPU.conv_mac.b ;
  /* hdlname = "mchip TPU conv_mac clk" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/mac.sv:6.16-6.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.conv_mac.clk ;
  /* hdlname = "mchip TPU conv_mac en" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/mac.sv:6.26-6.28|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.conv_mac.en ;
  /* hdlname = "mchip TPU conv_mac new_sum" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/mac.sv:9.25-9.32|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire [7:0] \mchip.TPU.conv_mac.new_sum ;
  /* hdlname = "mchip TPU conv_mac prod" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/mac.sv:9.34-9.38|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire [7:0] \mchip.TPU.conv_mac.prod ;
  /* hdlname = "mchip TPU conv_mac rst" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/mac.sv:6.21-6.24|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.conv_mac.rst ;
  /* hdlname = "mchip TPU conv_mac sum" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/mac.sv:7.32-7.35|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire [7:0] \mchip.TPU.conv_mac.sum ;
  /* hdlname = "mchip TPU conv_mac sum_reg D" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:6.33-6.34|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire [7:0] \mchip.TPU.conv_mac.sum_reg.D ;
  /* hdlname = "mchip TPU conv_mac sum_reg Q" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:7.33-7.34|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  reg [7:0] \mchip.TPU.conv_mac.sum_reg.Q ;
  /* hdlname = "mchip TPU conv_mac sum_reg clk" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:5.16-5.19|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.conv_mac.sum_reg.clk ;
  /* hdlname = "mchip TPU conv_mac sum_reg rst" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:5.21-5.24|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.conv_mac.sum_reg.rst ;
  /* hdlname = "mchip TPU conv_mac sum_reg we" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:5.26-5.28|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.conv_mac.sum_reg.we ;
  /* hdlname = "mchip TPU data_in" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:9.17-9.24|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* unused_bits = "1 2 3 4 5 6 7" */
  /* wiretype = "\\data_t" */
  wire [7:0] \mchip.TPU.data_in ;
  /* hdlname = "mchip TPU data_out" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:11.17-11.25|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* wiretype = "\\data_t" */
  wire [7:0] \mchip.TPU.data_out ;
  /* hdlname = "mchip TPU done" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:10.16-10.20|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.done ;
  /* hdlname = "mchip TPU insert_kernal" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:8.16-8.29|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.insert_kernal ;
  /* hdlname = "mchip TPU kernal_addr" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:28.16-28.27|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* wiretype = "\\conv_coord_t" */
  wire [3:0] \mchip.TPU.kernal_addr ;
  /* hdlname = "mchip TPU kernal_addr_x_counter Q" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:65.11-65.83|d24_mnguyen2_tpu/src/counter.sv:7.33-7.34|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  reg [3:0] \mchip.TPU.kernal_addr_x_counter.Q ;
  /* hdlname = "mchip TPU kernal_addr_x_counter Q_next" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:65.11-65.83|d24_mnguyen2_tpu/src/counter.sv:9.26-9.32|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire [3:0] \mchip.TPU.kernal_addr_x_counter.Q_next ;
  /* hdlname = "mchip TPU kernal_addr_x_counter clk" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:65.11-65.83|d24_mnguyen2_tpu/src/counter.sv:6.16-6.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.kernal_addr_x_counter.clk ;
  /* hdlname = "mchip TPU kernal_addr_x_counter en" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:65.11-65.83|d24_mnguyen2_tpu/src/counter.sv:6.26-6.28|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.kernal_addr_x_counter.en ;
  /* hdlname = "mchip TPU kernal_addr_x_counter rst" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:65.11-65.83|d24_mnguyen2_tpu/src/counter.sv:6.21-6.24|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.kernal_addr_x_counter.rst ;
  /* hdlname = "mchip TPU kernal_addr_y_counter Q" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:67.11-67.83|d24_mnguyen2_tpu/src/counter.sv:7.33-7.34|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  reg [3:0] \mchip.TPU.kernal_addr_y_counter.Q ;
  /* hdlname = "mchip TPU kernal_addr_y_counter Q_next" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:67.11-67.83|d24_mnguyen2_tpu/src/counter.sv:9.26-9.32|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire [3:0] \mchip.TPU.kernal_addr_y_counter.Q_next ;
  /* hdlname = "mchip TPU kernal_addr_y_counter clk" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:67.11-67.83|d24_mnguyen2_tpu/src/counter.sv:6.16-6.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.kernal_addr_y_counter.clk ;
  /* hdlname = "mchip TPU kernal_addr_y_counter rst" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:67.11-67.83|d24_mnguyen2_tpu/src/counter.sv:6.21-6.24|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.kernal_addr_y_counter.rst ;
  /* hdlname = "mchip TPU kernal_data" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:27.10-27.21|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* wiretype = "\\data_t" */
  wire [7:0] \mchip.TPU.kernal_data ;
  /* hdlname = "mchip TPU kernal_x_incr" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:61.24-61.37|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.kernal_x_incr ;
  /* hdlname = "mchip TPU mac_en" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:82.9-82.15|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.mac_en ;
  /* hdlname = "mchip TPU mac_rst" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:82.17-82.24|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.mac_rst ;
  /* hdlname = "mchip TPU matrix_data" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:41.10-41.21|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  /* wiretype = "\\data_t" */
  wire [7:0] \mchip.TPU.matrix_data ;
  /* hdlname = "mchip TPU ready" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:8.50-8.55|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.ready ;
  /* hdlname = "mchip TPU rst" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:7.21-7.24|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.rst ;
  /* hdlname = "mchip TPU write" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:8.43-8.48|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.write ;
  /* hdlname = "mchip TPU write_mode" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:8.31-8.41|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  wire \mchip.TPU.write_mode ;
  /* hdlname = "mchip clock" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/chip.sv:6.17-6.22" */
  wire \mchip.clock ;
  /* hdlname = "mchip io_in" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/chip.sv:4.24-4.29" */
  /* unused_bits = "5 6 7 8 9 10 11" */
  wire [11:0] \mchip.io_in ;
  /* hdlname = "mchip io_out" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/chip.sv:5.25-5.31" */
  wire [11:0] \mchip.io_out ;
  /* hdlname = "mchip reset" */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/chip.sv:7.17-7.22" */
  wire \mchip.reset ;
  assign _000_ = \mchip.TPU.kernal_addr_x_counter.Q [0] | ~(\mchip.TPU.kernal_addr_x_counter.Q [1]);
  assign _019_ = ~\mchip.TPU.base_addr_x_counter.Q [4];
  assign _020_ = \mchip.TPU.base_addr_x_counter.Q [0] & \mchip.TPU.base_addr_x_counter.Q [1];
  assign _021_ = \mchip.TPU.base_addr_x_counter.Q [2] & \mchip.TPU.base_addr_x_counter.Q [3];
  assign _022_ = _021_ & _020_;
  assign _017_ = _022_ & ~(_019_);
  assign _023_ = \mchip.TPU.kernal_addr_x_counter.Q [2] | \mchip.TPU.kernal_addr_x_counter.Q [3];
  assign _024_ = ~(_023_ | _000_);
  assign \mchip.TPU.kernal_addr_x_counter.Q_next [0] = ~(_024_ | \mchip.TPU.kernal_addr_x_counter.Q [0]);
  assign _025_ = \mchip.TPU.kernal_addr_x_counter.Q [0] & ~(\mchip.TPU.kernal_addr_x_counter.Q [1]);
  assign \mchip.TPU.kernal_addr_x_counter.Q_next [1] = _000_ ? _025_ : _023_;
  assign _026_ = \mchip.TPU.kernal_addr_x_counter.Q [1] & \mchip.TPU.kernal_addr_x_counter.Q [0];
  assign _027_ = _026_ ^ \mchip.TPU.kernal_addr_x_counter.Q [2];
  assign \mchip.TPU.kernal_addr_x_counter.Q_next [2] = _027_ & ~(_024_);
  assign _028_ = ~(_026_ & \mchip.TPU.kernal_addr_x_counter.Q [2]);
  assign _029_ = ~(_028_ ^ \mchip.TPU.kernal_addr_x_counter.Q [3]);
  assign \mchip.TPU.kernal_addr_x_counter.Q_next [3] = _029_ & ~(_024_);
  assign _030_ = ~\mchip.TPU.kernal_addr_y_counter.Q [0];
  assign _031_ = ~(\mchip.TPU.kernal_addr_y_counter.Q [2] | \mchip.TPU.kernal_addr_y_counter.Q [3]);
  assign _032_ = \mchip.TPU.kernal_addr_y_counter.Q [1] & ~(\mchip.TPU.kernal_addr_y_counter.Q [0]);
  assign _033_ = _032_ & _031_;
  assign \mchip.TPU.kernal_addr_y_counter.Q_next [0] = _030_ & ~(_033_);
  assign _034_ = ~_031_;
  assign _035_ = \mchip.TPU.kernal_addr_y_counter.Q [0] & ~(\mchip.TPU.kernal_addr_y_counter.Q [1]);
  assign \mchip.TPU.kernal_addr_y_counter.Q_next [1] = _032_ ? _034_ : _035_;
  assign _036_ = \mchip.TPU.kernal_addr_y_counter.Q [0] & \mchip.TPU.kernal_addr_y_counter.Q [1];
  assign _037_ = _036_ ^ \mchip.TPU.kernal_addr_y_counter.Q [2];
  assign \mchip.TPU.kernal_addr_y_counter.Q_next [2] = _037_ & ~(_033_);
  assign _038_ = ~(_036_ & \mchip.TPU.kernal_addr_y_counter.Q [2]);
  assign _039_ = ~(_038_ ^ \mchip.TPU.kernal_addr_y_counter.Q [3]);
  assign \mchip.TPU.kernal_addr_y_counter.Q_next [3] = _039_ & ~(_033_);
  assign _040_ = \mchip.TPU.base_addr_x_counter.Q [9] & \mchip.TPU.base_addr_x_counter.Q [8];
  assign _041_ = ~(\mchip.TPU.base_addr_x_counter.Q [6] & \mchip.TPU.base_addr_x_counter.Q [7]);
  assign _042_ = ~(\mchip.TPU.base_addr_x_counter.Q [5] & \mchip.TPU.base_addr_x_counter.Q [4]);
  assign _043_ = ~(_042_ | _041_);
  assign _044_ = ~(_043_ & _022_);
  assign _045_ = _044_ | ~(_040_);
  assign \mchip.TPU.base_addr_x_counter.Q_next [0] = _045_ & ~(\mchip.TPU.base_addr_x_counter.Q [0]);
  assign \mchip.TPU.base_addr_x_counter.Q_next [1] = \mchip.TPU.base_addr_x_counter.Q [0] ^ \mchip.TPU.base_addr_x_counter.Q [1];
  assign _046_ = ~\mchip.TPU.base_addr_x_counter.Q [2];
  assign _047_ = _020_ ^ _046_;
  assign \mchip.TPU.base_addr_x_counter.Q_next [2] = _045_ & ~(_047_);
  assign _048_ = ~(_020_ & \mchip.TPU.base_addr_x_counter.Q [2]);
  assign _049_ = _048_ ^ \mchip.TPU.base_addr_x_counter.Q [3];
  assign \mchip.TPU.base_addr_x_counter.Q_next [3] = _045_ & ~(_049_);
  assign _050_ = _022_ ^ _019_;
  assign \mchip.TPU.base_addr_x_counter.Q_next [4] = _045_ & ~(_050_);
  assign _051_ = ~(_017_ ^ \mchip.TPU.base_addr_x_counter.Q [5]);
  assign \mchip.TPU.base_addr_x_counter.Q_next [5] = _045_ & ~(_051_);
  assign _052_ = _022_ & ~(_042_);
  assign _053_ = ~(_052_ ^ \mchip.TPU.base_addr_x_counter.Q [6]);
  assign \mchip.TPU.base_addr_x_counter.Q_next [6] = _045_ & ~(_053_);
  assign _054_ = ~(_052_ & \mchip.TPU.base_addr_x_counter.Q [6]);
  assign _055_ = _054_ ^ \mchip.TPU.base_addr_x_counter.Q [7];
  assign \mchip.TPU.base_addr_x_counter.Q_next [7] = _045_ & ~(_055_);
  assign _056_ = _044_ ^ \mchip.TPU.base_addr_x_counter.Q [8];
  assign \mchip.TPU.base_addr_x_counter.Q_next [8] = _045_ & ~(_056_);
  assign _057_ = _044_ | ~(\mchip.TPU.base_addr_x_counter.Q [8]);
  assign _058_ = _057_ ^ \mchip.TPU.base_addr_x_counter.Q [9];
  assign \mchip.TPU.base_addr_x_counter.Q_next [9] = _045_ & ~(_058_);
  assign _059_ = \mchip.TPU.base_addr_y_counter.Q [9] & \mchip.TPU.base_addr_y_counter.Q [8];
  assign _060_ = \mchip.TPU.base_addr_y_counter.Q [0] & \mchip.TPU.base_addr_y_counter.Q [1];
  assign _061_ = \mchip.TPU.base_addr_y_counter.Q [2] & \mchip.TPU.base_addr_y_counter.Q [3];
  assign _062_ = _061_ & _060_;
  assign _063_ = ~(\mchip.TPU.base_addr_y_counter.Q [6] & \mchip.TPU.base_addr_y_counter.Q [7]);
  assign _064_ = ~(\mchip.TPU.base_addr_y_counter.Q [4] & \mchip.TPU.base_addr_y_counter.Q [5]);
  assign _065_ = ~(_064_ | _063_);
  assign _066_ = ~(_065_ & _062_);
  assign _067_ = _066_ | ~(_059_);
  assign \mchip.TPU.base_addr_y_counter.Q_next [0] = _067_ & ~(\mchip.TPU.base_addr_y_counter.Q [0]);
  assign \mchip.TPU.base_addr_y_counter.Q_next [1] = \mchip.TPU.base_addr_y_counter.Q [0] ^ \mchip.TPU.base_addr_y_counter.Q [1];
  assign _068_ = ~\mchip.TPU.base_addr_y_counter.Q [2];
  assign _069_ = _060_ ^ _068_;
  assign \mchip.TPU.base_addr_y_counter.Q_next [2] = _067_ & ~(_069_);
  assign _070_ = ~(_060_ & \mchip.TPU.base_addr_y_counter.Q [2]);
  assign _071_ = _070_ ^ \mchip.TPU.base_addr_y_counter.Q [3];
  assign \mchip.TPU.base_addr_y_counter.Q_next [3] = _067_ & ~(_071_);
  assign _072_ = ~\mchip.TPU.base_addr_y_counter.Q [4];
  assign _073_ = _062_ ^ _072_;
  assign \mchip.TPU.base_addr_y_counter.Q_next [4] = _067_ & ~(_073_);
  assign _074_ = ~(_062_ & \mchip.TPU.base_addr_y_counter.Q [4]);
  assign _075_ = _074_ ^ \mchip.TPU.base_addr_y_counter.Q [5];
  assign \mchip.TPU.base_addr_y_counter.Q_next [5] = _067_ & ~(_075_);
  assign _076_ = _062_ & ~(_064_);
  assign _077_ = ~(_076_ ^ \mchip.TPU.base_addr_y_counter.Q [6]);
  assign \mchip.TPU.base_addr_y_counter.Q_next [6] = _067_ & ~(_077_);
  assign _078_ = ~(_076_ & \mchip.TPU.base_addr_y_counter.Q [6]);
  assign _079_ = _078_ ^ \mchip.TPU.base_addr_y_counter.Q [7];
  assign \mchip.TPU.base_addr_y_counter.Q_next [7] = _067_ & ~(_079_);
  assign _080_ = _066_ ^ \mchip.TPU.base_addr_y_counter.Q [8];
  assign \mchip.TPU.base_addr_y_counter.Q_next [8] = _067_ & ~(_080_);
  assign _081_ = _066_ | ~(\mchip.TPU.base_addr_y_counter.Q [8]);
  assign _082_ = _081_ ^ \mchip.TPU.base_addr_y_counter.Q [9];
  assign \mchip.TPU.base_addr_y_counter.Q_next [9] = _067_ & ~(_082_);
  assign _083_ = ~\mchip.TPU.MATRIX_MAT.data [4];
  assign _084_ = ~\mchip.TPU.MATRIX_MAT.data [5];
  assign _085_ = ~\mchip.TPU.base_addr_x_counter.Q [0];
  assign _086_ = ~(\mchip.TPU.base_addr_x_counter.Q [0] ^ \mchip.TPU.kernal_addr_x_counter.Q [0]);
  assign _087_ = io_in[2] & ~(io_in[0]);
  assign _088_ = _087_ ? _085_ : _086_;
  assign _089_ = _088_ ? _083_ : _084_;
  assign _090_ = \mchip.TPU.base_addr_x_counter.Q [0] & \mchip.TPU.kernal_addr_x_counter.Q [0];
  assign _091_ = ~(\mchip.TPU.base_addr_x_counter.Q [1] ^ \mchip.TPU.kernal_addr_x_counter.Q [1]);
  assign _092_ = ~(_091_ ^ _090_);
  assign _093_ = _087_ ? \mchip.TPU.base_addr_x_counter.Q [1] : _092_;
  assign _094_ = ~\mchip.TPU.MATRIX_MAT.data [6];
  assign _095_ = ~\mchip.TPU.MATRIX_MAT.data [7];
  assign _096_ = _088_ ? _094_ : _095_;
  assign _097_ = _093_ ? _096_ : _089_;
  assign _098_ = ~(\mchip.TPU.base_addr_x_counter.Q [1] & \mchip.TPU.kernal_addr_x_counter.Q [1]);
  assign _099_ = _090_ & ~(_091_);
  assign _100_ = _098_ & ~(_099_);
  assign _101_ = _100_ ^ _046_;
  assign _102_ = _087_ ? \mchip.TPU.base_addr_x_counter.Q [2] : _101_;
  assign _103_ = ~\mchip.TPU.MATRIX_MAT.data [0];
  assign _104_ = ~\mchip.TPU.MATRIX_MAT.data [1];
  assign _105_ = _088_ ? _103_ : _104_;
  assign _106_ = ~\mchip.TPU.MATRIX_MAT.data [2];
  assign _107_ = ~\mchip.TPU.MATRIX_MAT.data [3];
  assign _108_ = _088_ ? _106_ : _107_;
  assign _109_ = _093_ ? _108_ : _105_;
  assign _110_ = _102_ ? _097_ : _109_;
  assign _111_ = ~\mchip.TPU.KERNAL_MAT.data [6];
  assign _112_ = ~\mchip.TPU.KERNAL_MAT.data [7];
  assign _113_ = \mchip.TPU.kernal_addr_y_counter.Q [0] ^ \mchip.TPU.kernal_addr_x_counter.Q [0];
  assign _114_ = _113_ ? _112_ : _111_;
  assign _115_ = \mchip.TPU.kernal_addr_y_counter.Q [0] & \mchip.TPU.kernal_addr_x_counter.Q [0];
  assign _116_ = \mchip.TPU.kernal_addr_y_counter.Q [1] ^ \mchip.TPU.kernal_addr_x_counter.Q [1];
  assign _117_ = _116_ ^ \mchip.TPU.kernal_addr_y_counter.Q [0];
  assign _118_ = _117_ ^ _115_;
  assign _119_ = ~\mchip.TPU.KERNAL_MAT.data [4];
  assign _120_ = ~\mchip.TPU.KERNAL_MAT.data [5];
  assign _121_ = _113_ ? _120_ : _119_;
  assign _122_ = _118_ ? _114_ : _121_;
  assign _123_ = _117_ & _115_;
  assign _124_ = ~(\mchip.TPU.kernal_addr_y_counter.Q [1] & \mchip.TPU.kernal_addr_x_counter.Q [1]);
  assign _125_ = _116_ & ~(_030_);
  assign _126_ = _124_ & ~(_125_);
  assign _127_ = ~(_126_ ^ \mchip.TPU.kernal_addr_y_counter.Q [1]);
  assign _128_ = _127_ ^ _123_;
  assign _129_ = ~\mchip.TPU.KERNAL_MAT.data [2];
  assign _130_ = ~\mchip.TPU.KERNAL_MAT.data [3];
  assign _131_ = _113_ ? _130_ : _129_;
  assign _132_ = ~\mchip.TPU.KERNAL_MAT.data [0];
  assign _133_ = ~\mchip.TPU.KERNAL_MAT.data [1];
  assign _134_ = _113_ ? _133_ : _132_;
  assign _135_ = _118_ ? _131_ : _134_;
  assign _136_ = _128_ ? _122_ : _135_;
  assign _137_ = _136_ | _110_;
  assign _138_ = \mchip.TPU.conv_mac.sum_reg.Q [0] & ~(_137_);
  assign \mchip.TPU.conv_mac.sum_reg.D [1] = _138_ ^ \mchip.TPU.conv_mac.sum_reg.Q [1];
  assign _139_ = _138_ & \mchip.TPU.conv_mac.sum_reg.Q [1];
  assign \mchip.TPU.conv_mac.sum_reg.D [2] = _139_ ^ \mchip.TPU.conv_mac.sum_reg.Q [2];
  assign _140_ = _139_ & \mchip.TPU.conv_mac.sum_reg.Q [2];
  assign \mchip.TPU.conv_mac.sum_reg.D [3] = _140_ ^ \mchip.TPU.conv_mac.sum_reg.Q [3];
  assign _141_ = ~(\mchip.TPU.conv_mac.sum_reg.Q [3] & \mchip.TPU.conv_mac.sum_reg.Q [2]);
  assign _142_ = _139_ & ~(_141_);
  assign \mchip.TPU.conv_mac.sum_reg.D [4] = _142_ ^ \mchip.TPU.conv_mac.sum_reg.Q [4];
  assign _143_ = _142_ & \mchip.TPU.conv_mac.sum_reg.Q [4];
  assign \mchip.TPU.conv_mac.sum_reg.D [5] = _143_ ^ \mchip.TPU.conv_mac.sum_reg.Q [5];
  assign _144_ = ~(\mchip.TPU.conv_mac.sum_reg.Q [5] & \mchip.TPU.conv_mac.sum_reg.Q [4]);
  assign _145_ = _142_ & ~(_144_);
  assign \mchip.TPU.conv_mac.sum_reg.D [6] = _145_ ^ \mchip.TPU.conv_mac.sum_reg.Q [6];
  assign _146_ = _145_ & \mchip.TPU.conv_mac.sum_reg.Q [6];
  assign \mchip.TPU.conv_mac.sum_reg.D [7] = _146_ ^ \mchip.TPU.conv_mac.sum_reg.Q [7];
  assign \mchip.TPU.conv_mac.sum_reg.D [0] = ~(_137_ ^ \mchip.TPU.conv_mac.sum_reg.Q [0]);
  assign \mchip.TPU.KERNAL_MAT.we  = io_in[1] & io_in[0];
  assign \mchip.TPU.MATRIX_MAT.we  = io_in[1] & ~(io_in[0]);
  assign _147_ = ~io_in[2];
  assign _148_ = ~(io_in[1] & io_in[2]);
  assign _149_ = _148_ | ~(io_in[0]);
  assign _150_ = io_in[3] & ~(_149_);
  assign \mchip.TPU.kernal_addr_x_counter.en  = _150_ | _147_;
  assign _151_ = _148_ | io_in[0];
  assign _152_ = _147_ & ~(_000_);
  assign _018_ = _151_ & ~(_152_);
  assign _153_ = io_in[3] & ~(_018_);
  assign \mchip.TPU.mac_rst  = _153_ | io_in[13];
  assign \mchip.TPU.done  = _153_ & ~(io_in[13]);
  assign _154_ = ~(\mchip.TPU.base_addr_y_counter.Q [1] & \mchip.TPU.kernal_addr_y_counter.Q [1]);
  assign _155_ = \mchip.TPU.base_addr_y_counter.Q [1] ^ \mchip.TPU.kernal_addr_y_counter.Q [1];
  assign _156_ = ~(\mchip.TPU.base_addr_y_counter.Q [0] & \mchip.TPU.kernal_addr_y_counter.Q [0]);
  assign _157_ = _155_ & ~(_156_);
  assign _158_ = _154_ & ~(_157_);
  assign _159_ = _061_ & ~(_158_);
  assign _160_ = _159_ & ~(_072_);
  assign _161_ = _021_ & ~(_100_);
  assign _162_ = _161_ & ~(_019_);
  assign _163_ = _162_ | _160_;
  assign \mchip.TPU.conv_mac.en  = _147_ & ~(_163_);
  assign _164_ = ~_113_;
  assign _165_ = \mchip.TPU.kernal_addr_y_counter.Q [1] & ~(_126_);
  assign _166_ = _127_ & _123_;
  assign _167_ = ~(_166_ | _165_);
  assign _168_ = _167_ & ~(_128_);
  assign _169_ = _164_ & ~(_118_);
  assign _170_ = ~_169_;
  assign _171_ = _168_ & ~(_170_);
  assign _172_ = ~(_171_ & io_in[4]);
  assign _173_ = _164_ & ~(_172_);
  assign _174_ = ~(_118_ & _113_);
  assign _175_ = _174_ & ~(_169_);
  assign _176_ = _173_ & ~(_175_);
  assign _177_ = _170_ ^ _128_;
  assign _178_ = _176_ & ~(_177_);
  assign _179_ = _169_ & ~(_128_);
  assign _180_ = ~(_179_ ^ _167_);
  assign _181_ = ~_180_;
  assign _182_ = _178_ & ~(_181_);
  assign _183_ = ~(_171_ & _164_);
  assign _184_ = _183_ | _175_;
  assign _185_ = _184_ | _177_;
  assign _186_ = _180_ & ~(_185_);
  assign _187_ = \mchip.TPU.KERNAL_MAT.data [0] & ~(_186_);
  assign _001_ = _187_ | _182_;
  assign _188_ = ~(_113_ & io_in[4]);
  assign _189_ = _188_ | ~(_175_);
  assign _190_ = _177_ & ~(_189_);
  assign _191_ = _190_ & ~(_180_);
  assign _192_ = _118_ | _164_;
  assign _193_ = _177_ & ~(_192_);
  assign _194_ = _193_ & ~(_180_);
  assign _195_ = \mchip.TPU.KERNAL_MAT.data [1] & ~(_194_);
  assign _002_ = _195_ | _191_;
  assign _196_ = ~_177_;
  assign _197_ = ~io_in[4];
  assign _198_ = _171_ | _197_;
  assign _199_ = _198_ | _113_;
  assign _200_ = _199_ | ~(_175_);
  assign _201_ = _200_ | _196_;
  assign _202_ = _181_ & ~(_201_);
  assign _203_ = ~(_118_ & _164_);
  assign _204_ = _177_ & ~(_203_);
  assign _205_ = _204_ & ~(_180_);
  assign _206_ = \mchip.TPU.KERNAL_MAT.data [2] & ~(_205_);
  assign _003_ = _206_ | _202_;
  assign _207_ = _188_ | _175_;
  assign _208_ = _177_ & ~(_207_);
  assign _209_ = _208_ & ~(_180_);
  assign _210_ = _177_ & ~(_174_);
  assign _211_ = _210_ & ~(_180_);
  assign _212_ = \mchip.TPU.KERNAL_MAT.data [3] & ~(_211_);
  assign _004_ = _212_ | _209_;
  assign _213_ = _199_ | _175_;
  assign _214_ = _213_ | _196_;
  assign _215_ = _181_ & ~(_214_);
  assign _216_ = _171_ | _113_;
  assign _217_ = _216_ | _175_;
  assign _218_ = _217_ | _196_;
  assign _219_ = _181_ & ~(_218_);
  assign _220_ = \mchip.TPU.KERNAL_MAT.data [4] & ~(_219_);
  assign _005_ = _220_ | _215_;
  assign _221_ = ~(_189_ | _177_);
  assign _222_ = _221_ & ~(_180_);
  assign _223_ = ~(_192_ | _177_);
  assign _224_ = _223_ & ~(_180_);
  assign _225_ = \mchip.TPU.KERNAL_MAT.data [5] & ~(_224_);
  assign _006_ = _225_ | _222_;
  assign _226_ = _200_ | _177_;
  assign _227_ = _181_ & ~(_226_);
  assign _228_ = ~(_203_ | _177_);
  assign _229_ = _228_ & ~(_180_);
  assign _230_ = \mchip.TPU.KERNAL_MAT.data [6] & ~(_229_);
  assign _007_ = _230_ | _227_;
  assign _231_ = ~(_207_ | _177_);
  assign _232_ = _231_ & ~(_180_);
  assign _233_ = ~(_177_ | _174_);
  assign _234_ = _233_ & ~(_180_);
  assign _235_ = \mchip.TPU.KERNAL_MAT.data [7] & ~(_234_);
  assign _008_ = _235_ | _232_;
  assign _236_ = _088_ & ~(_093_);
  assign _237_ = _236_ & ~(_102_);
  assign _238_ = \mchip.TPU.base_addr_x_counter.Q [2] & ~(_100_);
  assign _239_ = _238_ ^ \mchip.TPU.base_addr_x_counter.Q [3];
  assign _240_ = _087_ ? \mchip.TPU.base_addr_x_counter.Q [3] : _239_;
  assign _241_ = ~(_240_ ^ _237_);
  assign _242_ = ~_241_;
  assign _243_ = ~_088_;
  assign _244_ = _240_ | _102_;
  assign _245_ = _236_ & ~(_244_);
  assign _246_ = _161_ ^ \mchip.TPU.base_addr_x_counter.Q [4];
  assign _247_ = _087_ ? \mchip.TPU.base_addr_x_counter.Q [4] : _246_;
  assign _248_ = ~(_247_ ^ _245_);
  assign _249_ = _158_ ^ _068_;
  assign _250_ = _087_ ? \mchip.TPU.base_addr_y_counter.Q [2] : _249_;
  assign _251_ = ~(_156_ ^ _155_);
  assign _252_ = _087_ ? \mchip.TPU.base_addr_y_counter.Q [1] : _251_;
  assign _253_ = _252_ | _250_;
  assign _254_ = ~\mchip.TPU.base_addr_y_counter.Q [0];
  assign _255_ = ~(\mchip.TPU.base_addr_y_counter.Q [0] ^ \mchip.TPU.kernal_addr_y_counter.Q [0]);
  assign _256_ = _087_ ? _254_ : _255_;
  assign _257_ = _247_ | ~(_256_);
  assign _258_ = _257_ | _253_;
  assign _259_ = _245_ & ~(_258_);
  assign _260_ = \mchip.TPU.base_addr_y_counter.Q [2] & ~(_158_);
  assign _261_ = _260_ ^ \mchip.TPU.base_addr_y_counter.Q [3];
  assign _262_ = _087_ ? \mchip.TPU.base_addr_y_counter.Q [3] : _261_;
  assign _263_ = _259_ & ~(_262_);
  assign _264_ = _159_ ^ _072_;
  assign _265_ = _087_ ? _072_ : _264_;
  assign _266_ = _265_ ^ _263_;
  assign _267_ = _266_ ^ _248_;
  assign _268_ = ~(_262_ ^ _259_);
  assign _269_ = _268_ ^ _248_;
  assign _270_ = _245_ & ~(_257_);
  assign _271_ = _270_ & ~(_252_);
  assign _272_ = ~(_271_ ^ _250_);
  assign _273_ = _272_ ^ _248_;
  assign _274_ = ~(_270_ ^ _252_);
  assign _275_ = _274_ ^ _248_;
  assign _276_ = _245_ & ~(_247_);
  assign _277_ = _256_ ^ _276_;
  assign _278_ = _277_ ^ _248_;
  assign _279_ = _278_ | _275_;
  assign _280_ = _279_ | _273_;
  assign _281_ = _280_ | _269_;
  assign _282_ = _281_ | _267_;
  assign _283_ = ~_248_;
  assign _284_ = _262_ | ~(_265_);
  assign _285_ = _259_ & ~(_284_);
  assign _286_ = _285_ ^ _283_;
  assign _287_ = _286_ | _282_;
  assign _288_ = _287_ | _197_;
  assign _289_ = _288_ | _248_;
  assign _290_ = _289_ | _243_;
  assign _291_ = _093_ ^ _243_;
  assign _292_ = _291_ | _290_;
  assign _293_ = ~(_236_ ^ _102_);
  assign _294_ = _293_ | _292_;
  assign _295_ = _242_ & ~(_294_);
  assign _296_ = _287_ | _248_;
  assign _297_ = _296_ | _243_;
  assign _298_ = _297_ | _291_;
  assign _299_ = _298_ | _293_;
  assign _300_ = _242_ & ~(_299_);
  assign _301_ = \mchip.TPU.MATRIX_MAT.data [0] & ~(_300_);
  assign _009_ = _301_ | _295_;
  assign _302_ = ~_293_;
  assign _303_ = ~_291_;
  assign _304_ = _288_ | _283_;
  assign _305_ = _304_ | _088_;
  assign _306_ = _305_ | _303_;
  assign _307_ = _306_ | _302_;
  assign _308_ = _241_ & ~(_307_);
  assign _309_ = _287_ | _283_;
  assign _310_ = _309_ | _088_;
  assign _311_ = _310_ | _303_;
  assign _312_ = _311_ | _302_;
  assign _313_ = _241_ & ~(_312_);
  assign _314_ = \mchip.TPU.MATRIX_MAT.data [1] & ~(_313_);
  assign _010_ = _314_ | _308_;
  assign _315_ = _304_ | _243_;
  assign _316_ = _315_ | _303_;
  assign _317_ = _316_ | _302_;
  assign _318_ = _241_ & ~(_317_);
  assign _319_ = _309_ | _243_;
  assign _320_ = _319_ | _303_;
  assign _321_ = _320_ | _302_;
  assign _322_ = _241_ & ~(_321_);
  assign _323_ = \mchip.TPU.MATRIX_MAT.data [2] & ~(_322_);
  assign _011_ = _323_ | _318_;
  assign _324_ = _305_ | _291_;
  assign _325_ = _324_ | _302_;
  assign _326_ = _241_ & ~(_325_);
  assign _327_ = _310_ | _291_;
  assign _328_ = _327_ | _302_;
  assign _329_ = _241_ & ~(_328_);
  assign _330_ = \mchip.TPU.MATRIX_MAT.data [3] & ~(_329_);
  assign _012_ = _330_ | _326_;
  assign _331_ = _315_ | _291_;
  assign _332_ = _331_ | _302_;
  assign _333_ = _241_ & ~(_332_);
  assign _334_ = _319_ | _291_;
  assign _335_ = _334_ | _302_;
  assign _336_ = _241_ & ~(_335_);
  assign _337_ = \mchip.TPU.MATRIX_MAT.data [4] & ~(_336_);
  assign _013_ = _337_ | _333_;
  assign _338_ = _306_ | _293_;
  assign _339_ = _241_ & ~(_338_);
  assign _340_ = _311_ | _293_;
  assign _341_ = _241_ & ~(_340_);
  assign _342_ = \mchip.TPU.MATRIX_MAT.data [5] & ~(_341_);
  assign _014_ = _342_ | _339_;
  assign _343_ = _316_ | _293_;
  assign _344_ = _241_ & ~(_343_);
  assign _345_ = _320_ | _293_;
  assign _346_ = _241_ & ~(_345_);
  assign _347_ = \mchip.TPU.MATRIX_MAT.data [6] & ~(_346_);
  assign _015_ = _347_ | _344_;
  assign _348_ = _324_ | _293_;
  assign _349_ = _241_ & ~(_348_);
  assign _350_ = _327_ | _293_;
  assign _351_ = _241_ & ~(_350_);
  assign _352_ = \mchip.TPU.MATRIX_MAT.data [7] & ~(_351_);
  assign _016_ = _352_ | _349_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.KERNAL_MAT.data [0] <= 1'h0;
    else if (\mchip.TPU.KERNAL_MAT.we ) \mchip.TPU.KERNAL_MAT.data [0] <= _001_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.KERNAL_MAT.data [1] <= 1'h0;
    else if (\mchip.TPU.KERNAL_MAT.we ) \mchip.TPU.KERNAL_MAT.data [1] <= _002_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.KERNAL_MAT.data [2] <= 1'h0;
    else if (\mchip.TPU.KERNAL_MAT.we ) \mchip.TPU.KERNAL_MAT.data [2] <= _003_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.KERNAL_MAT.data [3] <= 1'h0;
    else if (\mchip.TPU.KERNAL_MAT.we ) \mchip.TPU.KERNAL_MAT.data [3] <= _004_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.KERNAL_MAT.data [4] <= 1'h0;
    else if (\mchip.TPU.KERNAL_MAT.we ) \mchip.TPU.KERNAL_MAT.data [4] <= _005_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.KERNAL_MAT.data [5] <= 1'h0;
    else if (\mchip.TPU.KERNAL_MAT.we ) \mchip.TPU.KERNAL_MAT.data [5] <= _006_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.KERNAL_MAT.data [6] <= 1'h0;
    else if (\mchip.TPU.KERNAL_MAT.we ) \mchip.TPU.KERNAL_MAT.data [6] <= _007_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:36.10-38.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.KERNAL_MAT.data [7] <= 1'h0;
    else if (\mchip.TPU.KERNAL_MAT.we ) \mchip.TPU.KERNAL_MAT.data [7] <= _008_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.MATRIX_MAT.data [0] <= 1'h0;
    else if (\mchip.TPU.MATRIX_MAT.we ) \mchip.TPU.MATRIX_MAT.data [0] <= _009_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.MATRIX_MAT.data [1] <= 1'h0;
    else if (\mchip.TPU.MATRIX_MAT.we ) \mchip.TPU.MATRIX_MAT.data [1] <= _010_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.MATRIX_MAT.data [2] <= 1'h0;
    else if (\mchip.TPU.MATRIX_MAT.we ) \mchip.TPU.MATRIX_MAT.data [2] <= _011_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.MATRIX_MAT.data [3] <= 1'h0;
    else if (\mchip.TPU.MATRIX_MAT.we ) \mchip.TPU.MATRIX_MAT.data [3] <= _012_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.MATRIX_MAT.data [4] <= 1'h0;
    else if (\mchip.TPU.MATRIX_MAT.we ) \mchip.TPU.MATRIX_MAT.data [4] <= _013_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.MATRIX_MAT.data [5] <= 1'h0;
    else if (\mchip.TPU.MATRIX_MAT.we ) \mchip.TPU.MATRIX_MAT.data [5] <= _014_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.MATRIX_MAT.data [6] <= 1'h0;
    else if (\mchip.TPU.MATRIX_MAT.we ) \mchip.TPU.MATRIX_MAT.data [6] <= _015_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:53.10-55.44|d24_mnguyen2_tpu/src/matrix.sv:14.3-19.6|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.MATRIX_MAT.data [7] <= 1'h0;
    else if (\mchip.TPU.MATRIX_MAT.we ) \mchip.TPU.MATRIX_MAT.data [7] <= _016_;
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:65.11-65.83|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.kernal_addr_x_counter.Q [0] <= 1'h0;
    else if (\mchip.TPU.kernal_addr_x_counter.en ) \mchip.TPU.kernal_addr_x_counter.Q [0] <= \mchip.TPU.kernal_addr_x_counter.Q_next [0];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:65.11-65.83|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.kernal_addr_x_counter.Q [1] <= 1'h0;
    else if (\mchip.TPU.kernal_addr_x_counter.en ) \mchip.TPU.kernal_addr_x_counter.Q [1] <= \mchip.TPU.kernal_addr_x_counter.Q_next [1];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:65.11-65.83|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.kernal_addr_x_counter.Q [2] <= 1'h0;
    else if (\mchip.TPU.kernal_addr_x_counter.en ) \mchip.TPU.kernal_addr_x_counter.Q [2] <= \mchip.TPU.kernal_addr_x_counter.Q_next [2];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:65.11-65.83|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.kernal_addr_x_counter.Q [3] <= 1'h0;
    else if (\mchip.TPU.kernal_addr_x_counter.en ) \mchip.TPU.kernal_addr_x_counter.Q [3] <= \mchip.TPU.kernal_addr_x_counter.Q_next [3];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:67.11-67.83|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.kernal_addr_y_counter.Q [0] <= 1'h0;
    else if (!_000_) \mchip.TPU.kernal_addr_y_counter.Q [0] <= \mchip.TPU.kernal_addr_y_counter.Q_next [0];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:67.11-67.83|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.kernal_addr_y_counter.Q [1] <= 1'h0;
    else if (!_000_) \mchip.TPU.kernal_addr_y_counter.Q [1] <= \mchip.TPU.kernal_addr_y_counter.Q_next [1];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:67.11-67.83|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.kernal_addr_y_counter.Q [2] <= 1'h0;
    else if (!_000_) \mchip.TPU.kernal_addr_y_counter.Q [2] <= \mchip.TPU.kernal_addr_y_counter.Q_next [2];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:67.11-67.83|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.kernal_addr_y_counter.Q [3] <= 1'h0;
    else if (!_000_) \mchip.TPU.kernal_addr_y_counter.Q [3] <= \mchip.TPU.kernal_addr_y_counter.Q_next [3];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_x_counter.Q [0] <= 1'h0;
    else if (!_018_) \mchip.TPU.base_addr_x_counter.Q [0] <= \mchip.TPU.base_addr_x_counter.Q_next [0];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_x_counter.Q [1] <= 1'h0;
    else if (!_018_) \mchip.TPU.base_addr_x_counter.Q [1] <= \mchip.TPU.base_addr_x_counter.Q_next [1];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_x_counter.Q [2] <= 1'h0;
    else if (!_018_) \mchip.TPU.base_addr_x_counter.Q [2] <= \mchip.TPU.base_addr_x_counter.Q_next [2];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_x_counter.Q [3] <= 1'h0;
    else if (!_018_) \mchip.TPU.base_addr_x_counter.Q [3] <= \mchip.TPU.base_addr_x_counter.Q_next [3];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_x_counter.Q [4] <= 1'h0;
    else if (!_018_) \mchip.TPU.base_addr_x_counter.Q [4] <= \mchip.TPU.base_addr_x_counter.Q_next [4];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_x_counter.Q [5] <= 1'h0;
    else if (!_018_) \mchip.TPU.base_addr_x_counter.Q [5] <= \mchip.TPU.base_addr_x_counter.Q_next [5];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_x_counter.Q [6] <= 1'h0;
    else if (!_018_) \mchip.TPU.base_addr_x_counter.Q [6] <= \mchip.TPU.base_addr_x_counter.Q_next [6];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_x_counter.Q [7] <= 1'h0;
    else if (!_018_) \mchip.TPU.base_addr_x_counter.Q [7] <= \mchip.TPU.base_addr_x_counter.Q_next [7];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_x_counter.Q [8] <= 1'h0;
    else if (!_018_) \mchip.TPU.base_addr_x_counter.Q [8] <= \mchip.TPU.base_addr_x_counter.Q_next [8];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:73.33-73.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_x_counter.Q [9] <= 1'h0;
    else if (!_018_) \mchip.TPU.base_addr_x_counter.Q [9] <= \mchip.TPU.base_addr_x_counter.Q_next [9];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_y_counter.Q [0] <= 1'h0;
    else if (_017_) \mchip.TPU.base_addr_y_counter.Q [0] <= \mchip.TPU.base_addr_y_counter.Q_next [0];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_y_counter.Q [1] <= 1'h0;
    else if (_017_) \mchip.TPU.base_addr_y_counter.Q [1] <= \mchip.TPU.base_addr_y_counter.Q_next [1];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_y_counter.Q [2] <= 1'h0;
    else if (_017_) \mchip.TPU.base_addr_y_counter.Q [2] <= \mchip.TPU.base_addr_y_counter.Q_next [2];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_y_counter.Q [3] <= 1'h0;
    else if (_017_) \mchip.TPU.base_addr_y_counter.Q [3] <= \mchip.TPU.base_addr_y_counter.Q_next [3];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_y_counter.Q [4] <= 1'h0;
    else if (_017_) \mchip.TPU.base_addr_y_counter.Q [4] <= \mchip.TPU.base_addr_y_counter.Q_next [4];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_y_counter.Q [5] <= 1'h0;
    else if (_017_) \mchip.TPU.base_addr_y_counter.Q [5] <= \mchip.TPU.base_addr_y_counter.Q_next [5];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_y_counter.Q [6] <= 1'h0;
    else if (_017_) \mchip.TPU.base_addr_y_counter.Q [6] <= \mchip.TPU.base_addr_y_counter.Q_next [6];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_y_counter.Q [7] <= 1'h0;
    else if (_017_) \mchip.TPU.base_addr_y_counter.Q [7] <= \mchip.TPU.base_addr_y_counter.Q_next [7];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_y_counter.Q [8] <= 1'h0;
    else if (_017_) \mchip.TPU.base_addr_y_counter.Q [8] <= \mchip.TPU.base_addr_y_counter.Q_next [8];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:74.33-74.99|d24_mnguyen2_tpu/src/counter.sv:11.3-15.19|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.TPU.base_addr_y_counter.Q [9] <= 1'h0;
    else if (_017_) \mchip.TPU.base_addr_y_counter.Q [9] <= \mchip.TPU.base_addr_y_counter.Q_next [9];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:9.3-13.14|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (\mchip.TPU.mac_rst ) \mchip.TPU.conv_mac.sum_reg.Q [0] <= 1'h0;
    else if (\mchip.TPU.conv_mac.en ) \mchip.TPU.conv_mac.sum_reg.Q [0] <= \mchip.TPU.conv_mac.sum_reg.D [0];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:9.3-13.14|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (\mchip.TPU.mac_rst ) \mchip.TPU.conv_mac.sum_reg.Q [1] <= 1'h0;
    else if (\mchip.TPU.conv_mac.en ) \mchip.TPU.conv_mac.sum_reg.Q [1] <= \mchip.TPU.conv_mac.sum_reg.D [1];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:9.3-13.14|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (\mchip.TPU.mac_rst ) \mchip.TPU.conv_mac.sum_reg.Q [2] <= 1'h0;
    else if (\mchip.TPU.conv_mac.en ) \mchip.TPU.conv_mac.sum_reg.Q [2] <= \mchip.TPU.conv_mac.sum_reg.D [2];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:9.3-13.14|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (\mchip.TPU.mac_rst ) \mchip.TPU.conv_mac.sum_reg.Q [3] <= 1'h0;
    else if (\mchip.TPU.conv_mac.en ) \mchip.TPU.conv_mac.sum_reg.Q [3] <= \mchip.TPU.conv_mac.sum_reg.D [3];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:9.3-13.14|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (\mchip.TPU.mac_rst ) \mchip.TPU.conv_mac.sum_reg.Q [4] <= 1'h0;
    else if (\mchip.TPU.conv_mac.en ) \mchip.TPU.conv_mac.sum_reg.Q [4] <= \mchip.TPU.conv_mac.sum_reg.D [4];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:9.3-13.14|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (\mchip.TPU.mac_rst ) \mchip.TPU.conv_mac.sum_reg.Q [5] <= 1'h0;
    else if (\mchip.TPU.conv_mac.en ) \mchip.TPU.conv_mac.sum_reg.Q [5] <= \mchip.TPU.conv_mac.sum_reg.D [5];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:9.3-13.14|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (\mchip.TPU.mac_rst ) \mchip.TPU.conv_mac.sum_reg.Q [6] <= 1'h0;
    else if (\mchip.TPU.conv_mac.en ) \mchip.TPU.conv_mac.sum_reg.Q [6] <= \mchip.TPU.conv_mac.sum_reg.D [6];
  /* \always_ff  = 32'd1 */
  /* src = "d24_mnguyen2_tpu/src/toplevel_chip.v:9.13-14.6|d24_mnguyen2_tpu/src/tpu.sv:87.7-90.32|d24_mnguyen2_tpu/src/register.sv:9.3-13.14|d24_mnguyen2_tpu/src/mac.sv:12.25-13.57|d24_mnguyen2_tpu/src/chip.sv:10.7-18.11" */
  always @(posedge io_in[12])
    if (\mchip.TPU.mac_rst ) \mchip.TPU.conv_mac.sum_reg.Q [7] <= 1'h0;
    else if (\mchip.TPU.conv_mac.en ) \mchip.TPU.conv_mac.sum_reg.Q [7] <= \mchip.TPU.conv_mac.sum_reg.D [7];
  assign io_out = { 2'h0, \mchip.TPU.conv_mac.sum_reg.Q , 3'h0, \mchip.TPU.done  };
  assign \mchip.TPU.KERNAL_MAT.D  = io_in[11:4];
  assign \mchip.TPU.KERNAL_MAT.Q  = 8'h00;
  assign \mchip.TPU.KERNAL_MAT.clk  = io_in[12];
  assign \mchip.TPU.KERNAL_MAT.rst  = io_in[13];
  assign \mchip.TPU.MATRIX_MAT.D  = io_in[11:4];
  assign \mchip.TPU.MATRIX_MAT.Q  = 8'h00;
  assign \mchip.TPU.MATRIX_MAT.clk  = io_in[12];
  assign \mchip.TPU.MATRIX_MAT.rst  = io_in[13];
  assign \mchip.TPU.base_addr  = { \mchip.TPU.base_addr_x_counter.Q [4:0], \mchip.TPU.base_addr_y_counter.Q [4:0] };
  assign \mchip.TPU.base_addr_x_counter.clk  = io_in[12];
  assign \mchip.TPU.base_addr_x_counter.rst  = io_in[13];
  assign \mchip.TPU.base_addr_y_counter.clk  = io_in[12];
  assign \mchip.TPU.base_addr_y_counter.rst  = io_in[13];
  assign \mchip.TPU.clk  = io_in[12];
  assign \mchip.TPU.conv_mac.a  = 8'h00;
  assign \mchip.TPU.conv_mac.b  = 8'h00;
  assign \mchip.TPU.conv_mac.clk  = io_in[12];
  assign \mchip.TPU.conv_mac.new_sum  = \mchip.TPU.conv_mac.sum_reg.D ;
  assign \mchip.TPU.conv_mac.prod  = 8'h00;
  assign \mchip.TPU.conv_mac.rst  = \mchip.TPU.mac_rst ;
  assign \mchip.TPU.conv_mac.sum  = \mchip.TPU.conv_mac.sum_reg.Q ;
  assign \mchip.TPU.conv_mac.sum_reg.clk  = io_in[12];
  assign \mchip.TPU.conv_mac.sum_reg.rst  = \mchip.TPU.mac_rst ;
  assign \mchip.TPU.conv_mac.sum_reg.we  = \mchip.TPU.conv_mac.en ;
  assign \mchip.TPU.data_in  = io_in[11:4];
  assign \mchip.TPU.data_out  = \mchip.TPU.conv_mac.sum_reg.Q ;
  assign \mchip.TPU.insert_kernal  = io_in[0];
  assign \mchip.TPU.kernal_addr  = { \mchip.TPU.kernal_addr_x_counter.Q [1:0], \mchip.TPU.kernal_addr_y_counter.Q [1:0] };
  assign \mchip.TPU.kernal_addr_x_counter.clk  = io_in[12];
  assign \mchip.TPU.kernal_addr_x_counter.rst  = io_in[13];
  assign \mchip.TPU.kernal_addr_y_counter.clk  = io_in[12];
  assign \mchip.TPU.kernal_addr_y_counter.rst  = io_in[13];
  assign \mchip.TPU.kernal_data  = 8'h00;
  assign \mchip.TPU.kernal_x_incr  = \mchip.TPU.kernal_addr_x_counter.en ;
  assign \mchip.TPU.mac_en  = \mchip.TPU.conv_mac.en ;
  assign \mchip.TPU.matrix_data  = 8'h00;
  assign \mchip.TPU.ready  = io_in[3];
  assign \mchip.TPU.rst  = io_in[13];
  assign \mchip.TPU.write  = io_in[1];
  assign \mchip.TPU.write_mode  = io_in[2];
  assign \mchip.clock  = io_in[12];
  assign \mchip.io_in  = io_in[11:0];
  assign \mchip.io_out  = { \mchip.TPU.conv_mac.sum_reg.Q , 3'h0, \mchip.TPU.done  };
  assign \mchip.reset  = io_in[13];
endmodule
