/* Generated by Yosys 0.25+83 (git sha1 755b753e1, aarch64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

/* top =  1  */
/* src = "d41_stroucki_corralgame/src/wrapper.v:2.9-12.18" */
module d41_stroucki_corralgame(io_in, io_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  /* force_downto = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:83.21-83.30|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21|/Users/anish/workspace/oss-cad-suite/libexec/../share/yosys/techmap.v:268.22-268.23" */
  wire [31:0] _098_;
  /* force_downto = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:0.0-0.0|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21|/Users/anish/workspace/oss-cad-suite/libexec/../share/yosys/techmap.v:270.23-270.24" */
  wire [2:0] _099_;
  /* force_downto = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:0.0-0.0|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21|/Users/anish/workspace/oss-cad-suite/libexec/../share/yosys/techmap.v:270.26-270.27" */
  wire [2:0] _100_;
  /* src = "d41_stroucki_corralgame/src/wrapper.v:3.26-3.31" */
  input [13:0] io_in;
  wire [13:0] io_in;
  /* src = "d41_stroucki_corralgame/src/wrapper.v:4.27-4.33" */
  output [13:0] io_out;
  wire [13:0] io_out;
  /* hdlname = "mchip clock" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:12.9-12.14" */
  wire \mchip.clock ;
  /* hdlname = "mchip cowboypos" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:27.15-27.24" */
  wire [3:0] \mchip.cowboypos ;
  /* hdlname = "mchip data" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:17.15-17.19" */
  wire [3:0] \mchip.data ;
  /* hdlname = "mchip enter" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:12.23-12.28" */
  wire \mchip.enter ;
  /* hdlname = "mchip gameenter" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:29.9-29.18" */
  wire \mchip.gameenter ;
  /* hdlname = "mchip gamegameover" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:29.20-29.32" */
  wire \mchip.gamegameover ;
  /* hdlname = "mchip gameinstance boltDest$func$d41_stroucki_corralgame/src/game.sv:154$21.boltStrength" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:101.13-101.25|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boltDest$func$d41_stroucki_corralgame/src/game.sv:154$21.boltStrength ;
  /* hdlname = "mchip gameinstance boltDest$func$d41_stroucki_corralgame/src/game.sv:154$21.cowboyLeftOfHorse" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:98.11-98.28|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.boltDest$func$d41_stroucki_corralgame/src/game.sv:154$21.cowboyLeftOfHorse ;
  /* hdlname = "mchip gameinstance boltDest$func$d41_stroucki_corralgame/src/game.sv:154$21.horsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:99.17-99.25|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.boltDest$func$d41_stroucki_corralgame/src/game.sv:154$21.horsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:144$17.horsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:89.13-89.21|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:144$17.horsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:144$17.targetHorsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:90.13-90.27|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:144$17.targetHorsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:146$18.horsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:89.13-89.21|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:146$18.horsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:146$18.targetHorsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:90.13-90.27|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:146$18.targetHorsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:151$20.horsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:89.13-89.21|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:151$20.horsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:151$20.targetHorsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:90.13-90.27|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:151$20.targetHorsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:154$22.horsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:89.13-89.21|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:154$22.horsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:154$22.targetHorsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:90.13-90.27|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:154$22.targetHorsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:156$23.horsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:89.13-89.21|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:156$23.horsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:156$23.targetHorsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:90.13-90.27|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:156$23.targetHorsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:175$24.horsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:89.13-89.21|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:175$24.horsePos ;
  /* hdlname = "mchip gameinstance boundHorse$func$d41_stroucki_corralgame/src/game.sv:175$24.targetHorsePos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:90.13-90.27|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:175$24.targetHorsePos ;
  /* hdlname = "mchip gameinstance clock" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:8.16-8.21|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.clock ;
  /* hdlname = "mchip gameinstance cowboyDest$func$d41_stroucki_corralgame/src/game.sv:150$19.cowboyLeftOfHorse" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:71.11-71.28|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.cowboyDest$func$d41_stroucki_corralgame/src/game.sv:150$19.cowboyLeftOfHorse ;
  /* hdlname = "mchip gameinstance cowboyDest$func$d41_stroucki_corralgame/src/game.sv:150$19.cowboyPos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:72.17-72.26|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.cowboyDest$func$d41_stroucki_corralgame/src/game.sv:150$19.cowboyPos ;
  /* hdlname = "mchip gameinstance cowboyDest$func$d41_stroucki_corralgame/src/game.sv:150$19.move" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:73.17-73.21|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.cowboyDest$func$d41_stroucki_corralgame/src/game.sv:150$19.move ;
  /* hdlname = "mchip gameinstance cowboyHitpoints" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:42.38-42.53|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [2:0] \mchip.gameinstance.cowboyHitpoints ;
  /* hdlname = "mchip gameinstance cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.cowboyLeftOfHorse" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:78.11-78.28|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.cowboyLeftOfHorse ;
  /* hdlname = "mchip gameinstance cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.cowboyPos" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:79.17-79.26|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.cowboyPos ;
  /* hdlname = "mchip gameinstance cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.dest" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:81.13-81.17|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [31:0] \mchip.gameinstance.cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.dest ;
  /* hdlname = "mchip gameinstance cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.move" */
  /* nosync = 32'd1 */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:80.17-80.21|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.move ;
  /* hdlname = "mchip gameinstance cowboyPos" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:12.22-12.31|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.cowboyPos ;
  /* hdlname = "mchip gameinstance cowboypos" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:22.15-22.24|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  reg [3:0] \mchip.gameinstance.cowboypos ;
  /* hdlname = "mchip gameinstance distance" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:61.15-61.23|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.distance ;
  /* hdlname = "mchip gameinstance enter" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:10.15-10.20|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.enter ;
  /* hdlname = "mchip gameinstance gameover" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:14.16-14.24|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.gameover ;
  /* hdlname = "mchip gameinstance horsepos" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:21.15-21.23|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.horsepos ;
  /* hdlname = "mchip gameinstance kickcount" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:42.27-42.36|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  reg [2:0] \mchip.gameinstance.kickcount ;
  /* hdlname = "mchip gameinstance kickflight" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:42.15-42.25|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  reg [2:0] \mchip.gameinstance.kickflight ;
  /* hdlname = "mchip gameinstance lfsrinstance i_Clk" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:31.13-32.27|d41_stroucki_corralgame/src/lfsr.v:20.10-20.15|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.lfsrinstance.i_Clk ;
  /* hdlname = "mchip gameinstance lfsrinstance i_Enable" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:31.13-32.27|d41_stroucki_corralgame/src/lfsr.v:21.10-21.18|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.lfsrinstance.i_Enable ;
  /* hdlname = "mchip gameinstance lfsrinstance o_LFSR_Data" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:31.13-32.27|d41_stroucki_corralgame/src/lfsr.v:27.26-27.37|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [4:0] \mchip.gameinstance.lfsrinstance.o_LFSR_Data ;
  /* hdlname = "mchip gameinstance lfsrinstance r_LFSR" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:31.13-32.27|d41_stroucki_corralgame/src/lfsr.v:31.20-31.26|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [5:1] \mchip.gameinstance.lfsrinstance.r_LFSR ;
  /* hdlname = "mchip gameinstance lfsrout" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:30.15-30.22|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [4:0] \mchip.gameinstance.lfsrout ;
  /* hdlname = "mchip gameinstance lostwon" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:15.16-15.23|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  reg \mchip.gameinstance.lostwon ;
  /* hdlname = "mchip gameinstance move" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:11.21-11.25|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [2:0] \mchip.gameinstance.move ;
  /* enum_value_000 = "\\IDLE" */
  /* enum_value_001 = "\\SETUP" */
  /* enum_value_010 = "\\KICK" */
  /* enum_value_011 = "\\WAIT" */
  /* enum_value_100 = "\\GAME" */
  /* hdlname = "mchip gameinstance nextState" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:19.26-19.35|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  /* wiretype = "\\state_t" */
  wire [2:0] \mchip.gameinstance.nextState ;
  /* hdlname = "mchip gameinstance p" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:34.16-34.17|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [30:0] \mchip.gameinstance.p ;
  /* hdlname = "mchip gameinstance pVal" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:37.15-37.19|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.pVal ;
  /* hdlname = "mchip gameinstance q" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:35.16-35.17|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [30:0] \mchip.gameinstance.q ;
  /* hdlname = "mchip gameinstance qVal" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:37.21-37.25|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.qVal ;
  /* hdlname = "mchip gameinstance randomVal" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:38.15-38.24|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [4:0] \mchip.gameinstance.randomVal ;
  /* hdlname = "mchip gameinstance ready" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:16.16-16.21|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.ready ;
  /* enum_value_000 = "\\IDLE" */
  /* enum_value_001 = "\\SETUP" */
  /* enum_value_010 = "\\KICK" */
  /* enum_value_011 = "\\WAIT" */
  /* enum_value_100 = "\\GAME" */
  /* hdlname = "mchip gameinstance state" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:19.11-19.16|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  /* wiretype = "\\state_t" */
  reg [2:0] \mchip.gameinstance.state  = 3'h1;
  /* hdlname = "mchip gameinstance targetGameover" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:24.9-24.23|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.targetGameover ;
  /* hdlname = "mchip gameinstance targetHorsepos" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:26.32-26.46|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [3:0] \mchip.gameinstance.targetHorsepos ;
  /* hdlname = "mchip gameinstance targetKickflight" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:25.15-25.31|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [2:0] \mchip.gameinstance.targetKickflight ;
  /* hdlname = "mchip gameinstance targetLostwon" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:24.25-24.38|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire \mchip.gameinstance.targetLostwon ;
  /* hdlname = "mchip gameinstance targetMove" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:25.50-25.60|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  wire [2:0] \mchip.gameinstance.targetMove ;
  /* hdlname = "mchip gamelostwon" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:29.34-29.45" */
  wire \mchip.gamelostwon ;
  /* hdlname = "mchip gamemove" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:30.15-30.23" */
  wire [2:0] \mchip.gamemove ;
  /* hdlname = "mchip gameover" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:16.25-16.33" */
  wire \mchip.gameover ;
  /* hdlname = "mchip gameready" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:29.47-29.56" */
  wire \mchip.gameready ;
  /* hdlname = "mchip io_in" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:8.22-8.27" */
  /* unused_bits = "6 7" */
  wire [7:0] \mchip.io_in ;
  /* hdlname = "mchip io_out" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:9.22-9.28" */
  wire [7:0] \mchip.io_out ;
  /* hdlname = "mchip lostwon" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:16.16-16.23" */
  reg \mchip.lostwon ;
  /* hdlname = "mchip move" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:13.15-13.19" */
  wire [2:0] \mchip.move ;
  /* hdlname = "mchip ready" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:16.9-16.14" */
  wire \mchip.ready ;
  /* hdlname = "mchip reset" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:12.16-12.21" */
  wire \mchip.reset ;
  /* enum_value_000 = "\\COWBOY" */
  /* enum_value_001 = "\\HORSE" */
  /* enum_value_010 = "\\GAME" */
  /* enum_value_011 = "\\IDLE" */
  /* hdlname = "mchip state" */
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:21.11-21.16" */
  /* wiretype = "\\state_t" */
  wire [2:0] \mchip.state ;
  assign _099_[0] = ~\mchip.gameinstance.kickcount [0];
  assign _042_ = ~(\mchip.gameinstance.state [1] | \mchip.gameinstance.state [0]);
  assign _043_ = _042_ & ~(\mchip.gameinstance.state [2]);
  assign _044_ = ~\mchip.gameinstance.state [2];
  assign _045_ = ~(\mchip.gameinstance.state [1] & \mchip.gameinstance.state [0]);
  assign _046_ = _044_ & ~(_045_);
  assign _047_ = \mchip.gameinstance.state [0] | ~(\mchip.gameinstance.state [1]);
  assign _048_ = _044_ & ~(_047_);
  assign _049_ = ~(_048_ | _046_);
  assign _050_ = _049_ & ~(_043_);
  assign _002_ = _050_ & ~(io_in[1]);
  assign \mchip.gameinstance.move [0] = io_in[2] & io_in[5];
  assign _051_ = _042_ & ~(_044_);
  assign _052_ = ~\mchip.gameinstance.cowboypos [2];
  assign _053_ = \mchip.gameinstance.cowboypos [1] | ~(\mchip.gameinstance.horsepos [1]);
  assign _054_ = ~\mchip.gameinstance.cowboypos [0];
  assign _055_ = \mchip.gameinstance.cowboypos [1] ^ \mchip.gameinstance.horsepos [1];
  assign _056_ = _054_ & ~(_055_);
  assign _057_ = _056_ | ~(_053_);
  assign _058_ = ~(_057_ & _052_);
  assign _059_ = \mchip.gameinstance.horsepos [1] ^ \mchip.gameinstance.cowboypos [3];
  assign _060_ = _059_ ^ _058_;
  assign _061_ = \mchip.gameinstance.cowboypos [3] | ~(\mchip.gameinstance.horsepos [1]);
  assign _062_ = _059_ | \mchip.gameinstance.cowboypos [2];
  assign _063_ = _057_ & ~(_062_);
  assign _064_ = _061_ & ~(_063_);
  assign _065_ = _052_ & ~(_053_);
  assign _066_ = _065_ ^ _059_;
  assign _067_ = _064_ ? _066_ : _060_;
  assign _068_ = _055_ ^ \mchip.gameinstance.cowboypos [0];
  assign _069_ = _064_ ? _055_ : _068_;
  assign _070_ = _064_ ? _053_ : _057_;
  assign _071_ = _070_ ^ \mchip.gameinstance.cowboypos [2];
  assign _072_ = _069_ | ~(_071_);
  assign _073_ = ~(_072_ | _067_);
  assign _074_ = io_in[5] & io_in[4];
  assign _075_ = ~_074_;
  assign _076_ = _075_ ^ _067_;
  assign _077_ = io_in[3] & io_in[5];
  assign _078_ = _077_ | _071_;
  assign _079_ = _077_ ^ _071_;
  assign _080_ = \mchip.gameinstance.move [0] & ~(_069_);
  assign _081_ = _079_ & ~(_080_);
  assign _082_ = _078_ & ~(_081_);
  assign _083_ = _076_ & ~(_082_);
  assign _084_ = _067_ & ~(_074_);
  assign _085_ = _084_ | _083_;
  assign _086_ = _085_ | _073_;
  assign _087_ = _051_ & ~(_086_);
  assign _088_ = _069_ & ~(_054_);
  assign _089_ = _067_ | ~(_071_);
  assign _090_ = _089_ | _088_;
  assign _091_ = ~(_090_ & _086_);
  assign _092_ = _051_ & ~(_091_);
  assign _093_ = _092_ | _087_;
  assign _000_ = _002_ & ~(_093_);
  assign _094_ = \mchip.gameinstance.state [0] ? \mchip.gameinstance.state [2] : \mchip.gameinstance.state [1];
  assign _095_ = ~(\mchip.gameinstance.kickcount [2] | \mchip.gameinstance.kickcount [1]);
  assign _096_ = ~_095_;
  assign _097_ = _048_ & ~(_096_);
  assign _004_ = _094_ & ~(_097_);
  assign _005_ = ~(_046_ | _043_);
  assign _006_ = _048_ & ~(_095_);
  assign _007_ = _006_ | io_in[1];
  assign _003_ = _005_ & ~(_007_);
  assign _008_ = _007_ | _093_;
  assign _001_ = _005_ & ~(_008_);
  assign _009_ = \mchip.gameinstance.state [0] & ~(\mchip.gameinstance.state [1]);
  assign \mchip.gameinstance.targetHorsepos [3] = _009_ & ~(\mchip.gameinstance.state [2]);
  assign _010_ = _077_ ^ \mchip.gameinstance.move [0];
  assign _098_[1] = _064_ ? _010_ : _077_;
  assign _011_ = ~(_077_ | \mchip.gameinstance.move [0]);
  assign _012_ = _011_ ^ _075_;
  assign _098_[2] = _064_ ? _012_ : _074_;
  assign _013_ = _011_ & ~(_074_);
  assign _098_[31] = _064_ & ~(_013_);
  assign _014_ = ~\mchip.gameinstance.kickflight [0];
  assign _015_ = \mchip.gameinstance.state [2] ? _042_ : _009_;
  assign \mchip.gameinstance.targetKickflight [0] = _015_ ? _051_ : _014_;
  assign _016_ = ~(\mchip.gameinstance.kickflight [1] ^ \mchip.gameinstance.kickflight [0]);
  assign \mchip.gameinstance.targetKickflight [1] = _016_ & ~(_015_);
  assign _017_ = ~(\mchip.gameinstance.kickflight [1] | \mchip.gameinstance.kickflight [0]);
  assign _018_ = _017_ ^ \mchip.gameinstance.kickflight [2];
  assign \mchip.gameinstance.targetKickflight [2] = _018_ & ~(_015_);
  assign _019_ = ~io_in[5];
  assign _020_ = _046_ & ~(_019_);
  assign _021_ = _020_ | _006_;
  assign _022_ = _086_ & ~(_090_);
  assign _023_ = _051_ & ~(_022_);
  assign _024_ = _023_ | \mchip.gameinstance.targetHorsepos [3];
  assign _025_ = _024_ | _021_;
  assign _026_ = _049_ & ~(_015_);
  assign \mchip.gameinstance.nextState [0] = _025_ & ~(_026_);
  assign _027_ = \mchip.gameinstance.kickflight [0] & ~(\mchip.gameinstance.kickflight [1]);
  assign _028_ = _027_ & ~(_018_);
  assign _029_ = _028_ | _096_;
  assign _030_ = _048_ & ~(_029_);
  assign _031_ = ~(_030_ | _020_);
  assign _032_ = _031_ & ~(_015_);
  assign \mchip.gameinstance.nextState [1] = ~(_032_ | _026_);
  assign _033_ = ~(_098_[31] | _098_[2]);
  assign _034_ = _098_[1] | \mchip.gameinstance.move [0];
  assign _035_ = _033_ & ~(_034_);
  assign _036_ = _035_ | _098_[31];
  assign _037_ = _077_ & _074_;
  assign _038_ = _013_ | _019_;
  assign _039_ = _038_ | _037_;
  assign _040_ = _039_ | _036_;
  assign \mchip.gameinstance.nextState [2] = _026_ & ~(_040_);
  assign _100_[1] = \mchip.gameinstance.kickcount [1] ^ \mchip.gameinstance.kickcount [0];
  assign _041_ = \mchip.gameinstance.kickcount [1] & \mchip.gameinstance.kickcount [0];
  assign _100_[2] = _041_ ^ \mchip.gameinstance.kickcount [2];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_002_)
      if (\mchip.gameinstance.targetHorsepos [3]) \mchip.gameinstance.cowboypos [0] <= 1'h0;
      else \mchip.gameinstance.cowboypos [0] <= \mchip.gameinstance.move [0];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_002_)
      if (\mchip.gameinstance.targetHorsepos [3]) \mchip.gameinstance.cowboypos [1] <= 1'h0;
      else \mchip.gameinstance.cowboypos [1] <= _098_[1];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_002_)
      if (\mchip.gameinstance.targetHorsepos [3]) \mchip.gameinstance.cowboypos [2] <= 1'h0;
      else \mchip.gameinstance.cowboypos [2] <= _098_[2];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_002_)
      if (\mchip.gameinstance.targetHorsepos [3]) \mchip.gameinstance.cowboypos [3] <= 1'h0;
      else \mchip.gameinstance.cowboypos [3] <= _098_[31];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_001_) \mchip.gameinstance.kickflight [0] <= \mchip.gameinstance.targetKickflight [0];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_001_) \mchip.gameinstance.kickflight [1] <= \mchip.gameinstance.targetKickflight [1];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_001_) \mchip.gameinstance.kickflight [2] <= \mchip.gameinstance.targetKickflight [2];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_000_)
      if (\mchip.gameinstance.targetHorsepos [3]) \mchip.gameinstance.kickcount [0] <= 1'h0;
      else \mchip.gameinstance.kickcount [0] <= _099_[0];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_000_)
      if (\mchip.gameinstance.targetHorsepos [3]) \mchip.gameinstance.kickcount [1] <= 1'h0;
      else \mchip.gameinstance.kickcount [1] <= _100_[1];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_000_)
      if (\mchip.gameinstance.targetHorsepos [3]) \mchip.gameinstance.kickcount [2] <= 1'h0;
      else \mchip.gameinstance.kickcount [2] <= _100_[2];
  reg \mchip.gameinstance.horsepos_reg[1] ;
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (_003_) \mchip.gameinstance.horsepos_reg[1]  <= \mchip.gameinstance.targetHorsepos [3];
  assign \mchip.gameinstance.horsepos [1] = \mchip.gameinstance.horsepos_reg[1] ;
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (io_in[1]) \mchip.gameinstance.lostwon  <= 1'h1;
    else if (_004_) \mchip.gameinstance.lostwon  <= 1'h0;
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (io_in[1]) \mchip.gameinstance.state [0] <= 1'h1;
    else \mchip.gameinstance.state [0] <= \mchip.gameinstance.nextState [0];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (io_in[1]) \mchip.gameinstance.state [1] <= 1'h0;
    else \mchip.gameinstance.state [1] <= \mchip.gameinstance.nextState [1];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/game.sv:193.3-208.6|d41_stroucki_corralgame/src/stroucki_top.sv:36.8-39.21" */
  always @(posedge io_in[0])
    if (io_in[1]) \mchip.gameinstance.state [2] <= 1'h0;
    else \mchip.gameinstance.state [2] <= \mchip.gameinstance.nextState [2];
  /* src = "d41_stroucki_corralgame/src/wrapper.v:7.26-10.14|d41_stroucki_corralgame/src/stroucki_top.sv:65.3-78.6" */
  always @(posedge io_in[0])
    if (!io_in[1]) \mchip.lostwon  <= \mchip.gameinstance.lostwon ;
  assign { _098_[30:3], _098_[0] } = { _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], _098_[31], \mchip.gameinstance.move [0] };
  assign _099_[2:1] = \mchip.gameinstance.kickcount [2:1];
  assign _100_[0] = _099_[0];
  assign io_out = { 8'h00, \mchip.lostwon , 5'h10 };
  assign \mchip.clock  = io_in[0];
  assign \mchip.cowboypos  = 4'h0;
  assign \mchip.data  = 4'h0;
  assign \mchip.enter  = io_in[5];
  assign \mchip.gameenter  = io_in[5];
  assign \mchip.gamegameover  = 1'h1;
  assign \mchip.gameinstance.boltDest$func$d41_stroucki_corralgame/src/game.sv:154$21.boltStrength  = 32'd0;
  assign \mchip.gameinstance.boltDest$func$d41_stroucki_corralgame/src/game.sv:154$21.cowboyLeftOfHorse  = 1'h0;
  assign \mchip.gameinstance.boltDest$func$d41_stroucki_corralgame/src/game.sv:154$21.horsePos  = 4'h0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:144$17.horsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:144$17.targetHorsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:146$18.horsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:146$18.targetHorsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:151$20.horsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:151$20.targetHorsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:154$22.horsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:154$22.targetHorsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:156$23.horsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:156$23.targetHorsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:175$24.horsePos  = 32'd0;
  assign \mchip.gameinstance.boundHorse$func$d41_stroucki_corralgame/src/game.sv:175$24.targetHorsePos  = 32'd0;
  assign \mchip.gameinstance.clock  = io_in[0];
  assign \mchip.gameinstance.cowboyDest$func$d41_stroucki_corralgame/src/game.sv:150$19.cowboyLeftOfHorse  = 1'h0;
  assign \mchip.gameinstance.cowboyDest$func$d41_stroucki_corralgame/src/game.sv:150$19.cowboyPos  = 4'h0;
  assign \mchip.gameinstance.cowboyDest$func$d41_stroucki_corralgame/src/game.sv:150$19.move  = 4'h0;
  assign \mchip.gameinstance.cowboyHitpoints  = 3'h1;
  assign \mchip.gameinstance.cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.cowboyLeftOfHorse  = 1'h0;
  assign \mchip.gameinstance.cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.cowboyPos  = 4'h0;
  assign \mchip.gameinstance.cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.dest  = 32'd0;
  assign \mchip.gameinstance.cowboyInBound$func$d41_stroucki_corralgame/src/game.sv:122$16.move  = 4'h0;
  assign \mchip.gameinstance.cowboyPos  = 4'h0;
  assign \mchip.gameinstance.distance  = { 3'h0, \mchip.gameinstance.cowboypos [0] };
  assign \mchip.gameinstance.enter  = io_in[5];
  assign \mchip.gameinstance.gameover  = 1'h1;
  assign { \mchip.gameinstance.horsepos [3:2], \mchip.gameinstance.horsepos [0] } = { \mchip.gameinstance.horsepos [1], 2'h0 };
  assign \mchip.gameinstance.lfsrinstance.i_Clk  = io_in[0];
  assign \mchip.gameinstance.lfsrinstance.i_Enable  = 1'h0;
  assign \mchip.gameinstance.lfsrinstance.o_LFSR_Data  = 5'h00;
  assign \mchip.gameinstance.lfsrinstance.r_LFSR  = 5'h00;
  assign \mchip.gameinstance.lfsrout  = 5'h00;
  assign \mchip.gameinstance.move [2:1] = 2'h0;
  assign \mchip.gameinstance.p  = 31'h2332210f;
  assign \mchip.gameinstance.pVal  = 4'hf;
  assign \mchip.gameinstance.q  = 31'h34543210;
  assign \mchip.gameinstance.qVal  = 4'h0;
  assign \mchip.gameinstance.randomVal  = 5'h00;
  assign \mchip.gameinstance.ready  = 1'h0;
  assign \mchip.gameinstance.targetGameover  = 1'h1;
  assign \mchip.gameinstance.targetHorsepos [2:0] = { 1'h0, \mchip.gameinstance.targetHorsepos [3], 1'h0 };
  assign \mchip.gameinstance.targetLostwon  = 1'h0;
  assign \mchip.gameinstance.targetMove  = { 2'h0, \mchip.gameinstance.move [0] };
  assign \mchip.gamelostwon  = \mchip.gameinstance.lostwon ;
  assign \mchip.gamemove  = { 2'h0, \mchip.gameinstance.move [0] };
  assign \mchip.gameover  = 1'h1;
  assign \mchip.gameready  = 1'h0;
  assign \mchip.io_in  = io_in[7:0];
  assign \mchip.io_out  = { 2'h0, \mchip.lostwon , 5'h10 };
  assign \mchip.move  = io_in[4:2];
  assign \mchip.ready  = 1'h0;
  assign \mchip.reset  = io_in[1];
  assign \mchip.state  = 3'h3;
endmodule
