/* Generated by Yosys 0.25+83 (git sha1 755b753e1, aarch64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

/* top =  1  */
/* src = "d40_jrecta_asyncfifo/src/wrapper.v:2.9-13.18" */
module d40_jrecta_asyncfifo(io_in, io_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:3.26-3.31" */
  input [13:0] io_in;
  wire [13:0] io_in;
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:4.27-4.33" */
  output [13:0] io_out;
  wire [13:0] io_out;
  /* hdlname = "mchip io_in" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/top.sv:2.43-2.48" */
  wire [7:0] \mchip.io_in ;
  /* hdlname = "mchip io_out" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/top.sv:3.44-3.50" */
  wire [7:0] \mchip.io_out ;
  /* hdlname = "mchip top backend empty" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:46.17-46.22|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.backend.empty ;
  /* hdlname = "mchip top backend rclk" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:43.21-43.25|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.backend.rclk ;
  /* hdlname = "mchip top backend re" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:43.27-43.29|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.backend.re ;
  /* hdlname = "mchip top backend rptr" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:45.33-45.37|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.backend.rptr ;
  /* hdlname = "mchip top backend rptr_b2g binary" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:124.27-124.33|d40_jrecta_asyncfifo/src/async-fifo.sv:61.25-62.38|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.backend.rptr_b2g.binary ;
  /* hdlname = "mchip top backend rptr_b2g gray" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:125.29-125.33|d40_jrecta_asyncfifo/src/async-fifo.sv:61.25-62.38|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.backend.rptr_b2g.gray ;
  /* hdlname = "mchip top backend rptr_gray" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:45.39-45.48|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.backend.rptr_gray ;
  /* hdlname = "mchip top backend rptr_reg clk" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:101.16-101.19|d40_jrecta_asyncfifo/src/async-fifo.sv:51.23-53.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.backend.rptr_reg.clk ;
  /* hdlname = "mchip top backend rptr_reg d" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:102.27-102.28|d40_jrecta_asyncfifo/src/async-fifo.sv:51.23-53.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.backend.rptr_reg.d ;
  /* hdlname = "mchip top backend rptr_reg en" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:101.26-101.28|d40_jrecta_asyncfifo/src/async-fifo.sv:51.23-53.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.backend.rptr_reg.en ;
  /* hdlname = "mchip top backend rptr_reg q" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:103.28-103.29|d40_jrecta_asyncfifo/src/async-fifo.sv:51.23-53.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  reg [3:0] \mchip.top.backend.rptr_reg.q ;
  /* hdlname = "mchip top backend rptr_reg rst" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:101.21-101.24|d40_jrecta_asyncfifo/src/async-fifo.sv:51.23-53.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.backend.rptr_reg.rst ;
  /* hdlname = "mchip top backend rst" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:43.16-43.19|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.backend.rst ;
  /* hdlname = "mchip top backend wptr_gray" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:44.32-44.41|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.backend.wptr_gray ;
  /* hdlname = "mchip top backend wptr_gray1" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:48.25-48.35|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.backend.wptr_gray1 ;
  /* hdlname = "mchip top backend wptr_gray2" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:48.37-48.47|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.backend.wptr_gray2 ;
  /* hdlname = "mchip top backend wptr_gray_sync clk" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:101.16-101.19|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.backend.wptr_gray_sync.clk ;
  /* hdlname = "mchip top backend wptr_gray_sync d" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:102.27-102.28|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [7:0] \mchip.top.backend.wptr_gray_sync.d ;
  /* hdlname = "mchip top backend wptr_gray_sync en" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:101.26-101.28|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.backend.wptr_gray_sync.en ;
  /* hdlname = "mchip top backend wptr_gray_sync q" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:103.28-103.29|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  reg [7:0] \mchip.top.backend.wptr_gray_sync.q ;
  /* hdlname = "mchip top backend wptr_gray_sync rst" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:101.21-101.24|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.backend.wptr_gray_sync.rst ;
  reg [2:0] \mchip.top.data[0] ;
  reg [2:0] \mchip.top.data[1] ;
  reg [2:0] \mchip.top.data[2] ;
  reg [2:0] \mchip.top.data[3] ;
  reg [2:0] \mchip.top.data[4] ;
  reg [2:0] \mchip.top.data[5] ;
  reg [2:0] \mchip.top.data[6] ;
  reg [2:0] \mchip.top.data[7] ;
  /* hdlname = "mchip top empty" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:11.17-11.22|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.empty ;
  /* hdlname = "mchip top frontend full" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:73.17-73.21|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.frontend.full ;
  /* hdlname = "mchip top frontend rptr_gray" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:71.32-71.41|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.frontend.rptr_gray ;
  /* hdlname = "mchip top frontend rptr_gray1" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:75.25-75.35|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.frontend.rptr_gray1 ;
  /* hdlname = "mchip top frontend rptr_gray2" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:75.37-75.47|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.frontend.rptr_gray2 ;
  /* hdlname = "mchip top frontend rptr_gray_sync clk" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:101.16-101.19|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.frontend.rptr_gray_sync.clk ;
  /* hdlname = "mchip top frontend rptr_gray_sync d" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:102.27-102.28|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [7:0] \mchip.top.frontend.rptr_gray_sync.d ;
  /* hdlname = "mchip top frontend rptr_gray_sync en" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:101.26-101.28|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.frontend.rptr_gray_sync.en ;
  /* hdlname = "mchip top frontend rptr_gray_sync q" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:103.28-103.29|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  reg [7:0] \mchip.top.frontend.rptr_gray_sync.q ;
  /* hdlname = "mchip top frontend rptr_gray_sync rst" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:101.21-101.24|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.frontend.rptr_gray_sync.rst ;
  /* hdlname = "mchip top frontend rst" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:70.16-70.19|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.frontend.rst ;
  /* hdlname = "mchip top frontend wclk" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:70.21-70.25|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.frontend.wclk ;
  /* hdlname = "mchip top frontend we" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:70.27-70.29|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.frontend.we ;
  /* hdlname = "mchip top frontend wptr" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:72.33-72.37|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.frontend.wptr ;
  /* hdlname = "mchip top frontend wptr_b2g binary" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:124.27-124.33|d40_jrecta_asyncfifo/src/async-fifo.sv:88.25-89.38|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.frontend.wptr_b2g.binary ;
  /* hdlname = "mchip top frontend wptr_b2g gray" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:125.29-125.33|d40_jrecta_asyncfifo/src/async-fifo.sv:88.25-89.38|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.frontend.wptr_b2g.gray ;
  /* hdlname = "mchip top frontend wptr_gray" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:72.39-72.48|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.frontend.wptr_gray ;
  /* hdlname = "mchip top frontend wptr_reg clk" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:101.16-101.19|d40_jrecta_asyncfifo/src/async-fifo.sv:78.23-80.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.frontend.wptr_reg.clk ;
  /* hdlname = "mchip top frontend wptr_reg d" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:102.27-102.28|d40_jrecta_asyncfifo/src/async-fifo.sv:78.23-80.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.frontend.wptr_reg.d ;
  /* hdlname = "mchip top frontend wptr_reg en" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:101.26-101.28|d40_jrecta_asyncfifo/src/async-fifo.sv:78.23-80.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.frontend.wptr_reg.en ;
  /* hdlname = "mchip top frontend wptr_reg q" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:103.28-103.29|d40_jrecta_asyncfifo/src/async-fifo.sv:78.23-80.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  reg [3:0] \mchip.top.frontend.wptr_reg.q ;
  /* hdlname = "mchip top frontend wptr_reg rst" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:101.21-101.24|d40_jrecta_asyncfifo/src/async-fifo.sv:78.23-80.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.frontend.wptr_reg.rst ;
  /* hdlname = "mchip top full" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:8.17-8.21|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.full ;
  /* hdlname = "mchip top rclk" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:10.16-10.20|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.rclk ;
  /* hdlname = "mchip top rdata" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:12.28-12.33|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [2:0] \mchip.top.rdata ;
  /* hdlname = "mchip top re" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:10.22-10.24|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.re ;
  /* hdlname = "mchip top rptr" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:17.42-17.46|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.rptr ;
  /* hdlname = "mchip top rptr_gray" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:17.48-17.57|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.rptr_gray ;
  /* hdlname = "mchip top rst" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:6.16-6.19|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.rst ;
  /* hdlname = "mchip top wclk" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:7.16-7.20|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.wclk ;
  /* hdlname = "mchip top wdata" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:9.27-9.32|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [2:0] \mchip.top.wdata ;
  /* hdlname = "mchip top we" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:7.22-7.24|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire \mchip.top.we ;
  /* hdlname = "mchip top wptr" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:17.25-17.29|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.wptr ;
  /* hdlname = "mchip top wptr_gray" */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:17.31-17.40|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  wire [3:0] \mchip.top.wptr_gray ;
  assign \mchip.top.frontend.wptr_reg.d [0] = ~\mchip.top.frontend.wptr_reg.q [0];
  assign \mchip.top.backend.rptr_reg.d [0] = ~\mchip.top.backend.rptr_reg.q [0];
  assign \mchip.top.backend.rptr_gray [0] = \mchip.top.backend.rptr_reg.q [1] ^ \mchip.top.backend.rptr_reg.q [0];
  assign _036_ = ~(\mchip.top.backend.rptr_gray [0] ^ \mchip.top.backend.wptr_gray_sync.q [0]);
  assign \mchip.top.backend.rptr_gray [1] = \mchip.top.backend.rptr_reg.q [2] ^ \mchip.top.backend.rptr_reg.q [1];
  assign _037_ = \mchip.top.backend.rptr_gray [1] ^ \mchip.top.backend.wptr_gray_sync.q [1];
  assign _038_ = _036_ & ~(_037_);
  assign _039_ = \mchip.top.backend.wptr_gray_sync.q [3] ^ \mchip.top.backend.rptr_reg.q [3];
  assign \mchip.top.backend.rptr_gray [2] = \mchip.top.backend.rptr_reg.q [3] ^ \mchip.top.backend.rptr_reg.q [2];
  assign _040_ = \mchip.top.backend.rptr_gray [2] ^ \mchip.top.backend.wptr_gray_sync.q [2];
  assign _041_ = _040_ | _039_;
  assign \mchip.top.backend.empty  = _038_ & ~(_041_);
  assign \mchip.top.frontend.wptr_gray [2] = \mchip.top.frontend.wptr_reg.q [2] ^ \mchip.top.frontend.wptr_reg.q [3];
  assign _042_ = \mchip.top.frontend.wptr_gray [2] ^ \mchip.top.frontend.rptr_gray_sync.q [2];
  assign _043_ = ~(\mchip.top.frontend.rptr_gray_sync.q [3] ^ \mchip.top.frontend.wptr_reg.q [3]);
  assign _044_ = _042_ & ~(_043_);
  assign \mchip.top.frontend.wptr_gray [1] = \mchip.top.frontend.wptr_reg.q [1] ^ \mchip.top.frontend.wptr_reg.q [2];
  assign _045_ = \mchip.top.frontend.wptr_gray [1] ^ \mchip.top.frontend.rptr_gray_sync.q [1];
  assign \mchip.top.frontend.wptr_gray [0] = \mchip.top.frontend.wptr_reg.q [1] ^ \mchip.top.frontend.wptr_reg.q [0];
  assign _046_ = \mchip.top.frontend.wptr_gray [0] ^ \mchip.top.frontend.rptr_gray_sync.q [0];
  assign _047_ = _046_ | _045_;
  assign \mchip.top.frontend.full  = _044_ & ~(_047_);
  assign _048_ = ~\mchip.top.backend.rptr_reg.q [2];
  assign _049_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[1] [0] : \mchip.top.data[0] [0];
  assign _050_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[3] [0] : \mchip.top.data[2] [0];
  assign _051_ = \mchip.top.backend.rptr_reg.q [1] ? _050_ : _049_;
  assign _052_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[5] [0] : \mchip.top.data[4] [0];
  assign _053_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[7] [0] : \mchip.top.data[6] [0];
  assign _054_ = \mchip.top.backend.rptr_reg.q [1] ? _053_ : _052_;
  assign io_out[5] = \mchip.top.backend.rptr_reg.q [2] ? _054_ : _051_;
  assign _008_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[1] [1] : \mchip.top.data[0] [1];
  assign _009_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[3] [1] : \mchip.top.data[2] [1];
  assign _010_ = \mchip.top.backend.rptr_reg.q [1] ? _009_ : _008_;
  assign _011_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[5] [1] : \mchip.top.data[4] [1];
  assign _012_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[7] [1] : \mchip.top.data[6] [1];
  assign _013_ = \mchip.top.backend.rptr_reg.q [1] ? _012_ : _011_;
  assign io_out[6] = \mchip.top.backend.rptr_reg.q [2] ? _013_ : _010_;
  assign _014_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[1] [2] : \mchip.top.data[0] [2];
  assign _015_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[3] [2] : \mchip.top.data[2] [2];
  assign _016_ = \mchip.top.backend.rptr_reg.q [1] ? _015_ : _014_;
  assign _017_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[5] [2] : \mchip.top.data[4] [2];
  assign _018_ = \mchip.top.backend.rptr_reg.q [0] ? \mchip.top.data[7] [2] : \mchip.top.data[6] [2];
  assign _019_ = \mchip.top.backend.rptr_reg.q [1] ? _018_ : _017_;
  assign io_out[7] = \mchip.top.backend.rptr_reg.q [2] ? _019_ : _016_;
  assign \mchip.top.frontend.wptr_reg.en  = io_in[3] & ~(\mchip.top.frontend.full );
  assign _020_ = \mchip.top.frontend.wptr_reg.q [2] | ~(\mchip.top.frontend.wptr_reg.q [1]);
  assign _021_ = _020_ | \mchip.top.frontend.wptr_reg.q [0];
  assign _002_ = \mchip.top.frontend.wptr_reg.en  & ~(_021_);
  assign _022_ = _020_ | \mchip.top.frontend.wptr_reg.d [0];
  assign _003_ = \mchip.top.frontend.wptr_reg.en  & ~(_022_);
  assign _023_ = \mchip.top.frontend.wptr_reg.q [1] | ~(\mchip.top.frontend.wptr_reg.q [2]);
  assign _024_ = _023_ | \mchip.top.frontend.wptr_reg.q [0];
  assign _004_ = \mchip.top.frontend.wptr_reg.en  & ~(_024_);
  assign _025_ = _023_ | \mchip.top.frontend.wptr_reg.d [0];
  assign _005_ = \mchip.top.frontend.wptr_reg.en  & ~(_025_);
  assign _026_ = ~(\mchip.top.frontend.wptr_reg.q [1] & \mchip.top.frontend.wptr_reg.q [2]);
  assign _027_ = _026_ | \mchip.top.frontend.wptr_reg.q [0];
  assign _006_ = \mchip.top.frontend.wptr_reg.en  & ~(_027_);
  assign _028_ = _026_ | \mchip.top.frontend.wptr_reg.d [0];
  assign _007_ = \mchip.top.frontend.wptr_reg.en  & ~(_028_);
  assign _029_ = \mchip.top.frontend.wptr_reg.q [1] | \mchip.top.frontend.wptr_reg.q [2];
  assign _030_ = _029_ | \mchip.top.frontend.wptr_reg.q [0];
  assign _000_ = \mchip.top.frontend.wptr_reg.en  & ~(_030_);
  assign _031_ = _029_ | \mchip.top.frontend.wptr_reg.d [0];
  assign _001_ = \mchip.top.frontend.wptr_reg.en  & ~(_031_);
  assign \mchip.top.backend.rptr_reg.en  = io_in[4] & ~(\mchip.top.backend.empty );
  assign _032_ = ~(\mchip.top.backend.rptr_reg.q [1] & \mchip.top.backend.rptr_reg.q [0]);
  assign \mchip.top.backend.rptr_reg.d [2] = _032_ ^ _048_;
  assign _033_ = \mchip.top.backend.rptr_reg.q [2] & ~(_032_);
  assign \mchip.top.backend.rptr_reg.d [3] = _033_ ^ \mchip.top.backend.rptr_reg.q [3];
  assign _034_ = ~(\mchip.top.frontend.wptr_reg.q [1] & \mchip.top.frontend.wptr_reg.q [0]);
  assign \mchip.top.frontend.wptr_reg.d [2] = ~(_034_ ^ \mchip.top.frontend.wptr_reg.q [2]);
  assign _035_ = \mchip.top.frontend.wptr_reg.q [2] & ~(_034_);
  assign \mchip.top.frontend.wptr_reg.d [3] = _035_ ^ \mchip.top.frontend.wptr_reg.q [3];
  always @(posedge io_in[12])
    if (_007_) \mchip.top.data[7] [0] <= io_in[5];
  always @(posedge io_in[12])
    if (_007_) \mchip.top.data[7] [1] <= io_in[6];
  always @(posedge io_in[12])
    if (_007_) \mchip.top.data[7] [2] <= io_in[7];
  always @(posedge io_in[12])
    if (_001_) \mchip.top.data[1] [0] <= io_in[5];
  always @(posedge io_in[12])
    if (_001_) \mchip.top.data[1] [1] <= io_in[6];
  always @(posedge io_in[12])
    if (_001_) \mchip.top.data[1] [2] <= io_in[7];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.rptr_gray_sync.q [0] <= 1'h0;
    else \mchip.top.frontend.rptr_gray_sync.q [0] <= \mchip.top.frontend.rptr_gray_sync.q [4];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.rptr_gray_sync.q [1] <= 1'h0;
    else \mchip.top.frontend.rptr_gray_sync.q [1] <= \mchip.top.frontend.rptr_gray_sync.q [5];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.rptr_gray_sync.q [2] <= 1'h0;
    else \mchip.top.frontend.rptr_gray_sync.q [2] <= \mchip.top.frontend.rptr_gray_sync.q [6];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.rptr_gray_sync.q [3] <= 1'h0;
    else \mchip.top.frontend.rptr_gray_sync.q [3] <= \mchip.top.frontend.rptr_gray_sync.q [7];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.rptr_gray_sync.q [4] <= 1'h0;
    else \mchip.top.frontend.rptr_gray_sync.q [4] <= \mchip.top.backend.rptr_gray [0];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.rptr_gray_sync.q [5] <= 1'h0;
    else \mchip.top.frontend.rptr_gray_sync.q [5] <= \mchip.top.backend.rptr_gray [1];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.rptr_gray_sync.q [6] <= 1'h0;
    else \mchip.top.frontend.rptr_gray_sync.q [6] <= \mchip.top.backend.rptr_gray [2];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:83.25-85.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.rptr_gray_sync.q [7] <= 1'h0;
    else \mchip.top.frontend.rptr_gray_sync.q [7] <= \mchip.top.backend.rptr_reg.q [3];
  always @(posedge io_in[12])
    if (_002_) \mchip.top.data[2] [0] <= io_in[5];
  always @(posedge io_in[12])
    if (_002_) \mchip.top.data[2] [1] <= io_in[6];
  always @(posedge io_in[12])
    if (_002_) \mchip.top.data[2] [2] <= io_in[7];
  always @(posedge io_in[12])
    if (_006_) \mchip.top.data[6] [0] <= io_in[5];
  always @(posedge io_in[12])
    if (_006_) \mchip.top.data[6] [1] <= io_in[6];
  always @(posedge io_in[12])
    if (_006_) \mchip.top.data[6] [2] <= io_in[7];
  always @(posedge io_in[12])
    if (_005_) \mchip.top.data[5] [0] <= io_in[5];
  always @(posedge io_in[12])
    if (_005_) \mchip.top.data[5] [1] <= io_in[6];
  always @(posedge io_in[12])
    if (_005_) \mchip.top.data[5] [2] <= io_in[7];
  always @(posedge io_in[12])
    if (_004_) \mchip.top.data[4] [0] <= io_in[5];
  always @(posedge io_in[12])
    if (_004_) \mchip.top.data[4] [1] <= io_in[6];
  always @(posedge io_in[12])
    if (_004_) \mchip.top.data[4] [2] <= io_in[7];
  always @(posedge io_in[12])
    if (_000_) \mchip.top.data[0] [0] <= io_in[5];
  always @(posedge io_in[12])
    if (_000_) \mchip.top.data[0] [1] <= io_in[6];
  always @(posedge io_in[12])
    if (_000_) \mchip.top.data[0] [2] <= io_in[7];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.wptr_gray_sync.q [0] <= 1'h0;
    else \mchip.top.backend.wptr_gray_sync.q [0] <= \mchip.top.backend.wptr_gray_sync.q [4];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.wptr_gray_sync.q [1] <= 1'h0;
    else \mchip.top.backend.wptr_gray_sync.q [1] <= \mchip.top.backend.wptr_gray_sync.q [5];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.wptr_gray_sync.q [2] <= 1'h0;
    else \mchip.top.backend.wptr_gray_sync.q [2] <= \mchip.top.backend.wptr_gray_sync.q [6];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.wptr_gray_sync.q [3] <= 1'h0;
    else \mchip.top.backend.wptr_gray_sync.q [3] <= \mchip.top.backend.wptr_gray_sync.q [7];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.wptr_gray_sync.q [4] <= 1'h0;
    else \mchip.top.backend.wptr_gray_sync.q [4] <= \mchip.top.frontend.wptr_gray [0];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.wptr_gray_sync.q [5] <= 1'h0;
    else \mchip.top.backend.wptr_gray_sync.q [5] <= \mchip.top.frontend.wptr_gray [1];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.wptr_gray_sync.q [6] <= 1'h0;
    else \mchip.top.backend.wptr_gray_sync.q [6] <= \mchip.top.frontend.wptr_gray [2];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:56.25-58.64|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.wptr_gray_sync.q [7] <= 1'h0;
    else \mchip.top.backend.wptr_gray_sync.q [7] <= \mchip.top.frontend.wptr_reg.q [3];
  always @(posedge io_in[12])
    if (_003_) \mchip.top.data[3] [0] <= io_in[5];
  always @(posedge io_in[12])
    if (_003_) \mchip.top.data[3] [1] <= io_in[6];
  always @(posedge io_in[12])
    if (_003_) \mchip.top.data[3] [2] <= io_in[7];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:78.23-80.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.wptr_reg.q [0] <= 1'h0;
    else if (\mchip.top.frontend.wptr_reg.en ) \mchip.top.frontend.wptr_reg.q [0] <= \mchip.top.frontend.wptr_reg.d [0];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:78.23-80.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.wptr_reg.q [1] <= 1'h0;
    else if (\mchip.top.frontend.wptr_reg.en ) \mchip.top.frontend.wptr_reg.q [1] <= \mchip.top.frontend.wptr_gray [0];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:78.23-80.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.wptr_reg.q [2] <= 1'h0;
    else if (\mchip.top.frontend.wptr_reg.en ) \mchip.top.frontend.wptr_reg.q [2] <= \mchip.top.frontend.wptr_reg.d [2];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:27.27-31.12|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:78.23-80.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[12])
    if (io_in[2]) \mchip.top.frontend.wptr_reg.q [3] <= 1'h0;
    else if (\mchip.top.frontend.wptr_reg.en ) \mchip.top.frontend.wptr_reg.q [3] <= \mchip.top.frontend.wptr_reg.d [3];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:51.23-53.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.rptr_reg.q [0] <= 1'h0;
    else if (\mchip.top.backend.rptr_reg.en ) \mchip.top.backend.rptr_reg.q [0] <= \mchip.top.backend.rptr_reg.d [0];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:51.23-53.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.rptr_reg.q [1] <= 1'h0;
    else if (\mchip.top.backend.rptr_reg.en ) \mchip.top.backend.rptr_reg.q [1] <= \mchip.top.backend.rptr_gray [0];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:51.23-53.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.rptr_reg.q [2] <= 1'h0;
    else if (\mchip.top.backend.rptr_reg.en ) \mchip.top.backend.rptr_reg.q [2] <= \mchip.top.backend.rptr_reg.d [2];
  /* \always_ff  = 32'd1 */
  /* src = "d40_jrecta_asyncfifo/src/wrapper.v:8.35-11.14|d40_jrecta_asyncfifo/src/async-fifo.sv:34.26-38.13|d40_jrecta_asyncfifo/src/async-fifo.sv:104.3-108.14|d40_jrecta_asyncfifo/src/async-fifo.sv:51.23-53.43|d40_jrecta_asyncfifo/src/top.sv:7.38-16.26" */
  always @(posedge io_in[1])
    if (io_in[2]) \mchip.top.backend.rptr_reg.q [3] <= 1'h0;
    else if (\mchip.top.backend.rptr_reg.en ) \mchip.top.backend.rptr_reg.q [3] <= \mchip.top.backend.rptr_reg.d [3];
  assign { io_out[13:8], io_out[4:0] } = { 6'h00, \mchip.top.backend.empty , \mchip.top.frontend.full , 3'h0 };
  assign \mchip.io_in  = { io_in[7:1], io_in[12] };
  assign \mchip.io_out  = { io_out[7:5], \mchip.top.backend.empty , \mchip.top.frontend.full , 3'h0 };
  assign \mchip.top.backend.rclk  = io_in[1];
  assign \mchip.top.backend.re  = io_in[4];
  assign \mchip.top.backend.rptr  = \mchip.top.backend.rptr_reg.q ;
  assign \mchip.top.backend.rptr_b2g.binary  = \mchip.top.backend.rptr_reg.q ;
  assign \mchip.top.backend.rptr_b2g.gray  = { \mchip.top.backend.rptr_reg.q [3], \mchip.top.backend.rptr_gray [2:0] };
  assign \mchip.top.backend.rptr_gray [3] = \mchip.top.backend.rptr_reg.q [3];
  assign \mchip.top.backend.rptr_reg.clk  = io_in[1];
  assign \mchip.top.backend.rptr_reg.d [1] = \mchip.top.backend.rptr_gray [0];
  assign \mchip.top.backend.rptr_reg.rst  = io_in[2];
  assign \mchip.top.backend.rst  = io_in[2];
  assign \mchip.top.backend.wptr_gray  = { \mchip.top.frontend.wptr_reg.q [3], \mchip.top.frontend.wptr_gray [2:0] };
  assign \mchip.top.backend.wptr_gray1  = \mchip.top.backend.wptr_gray_sync.q [7:4];
  assign \mchip.top.backend.wptr_gray2  = \mchip.top.backend.wptr_gray_sync.q [3:0];
  assign \mchip.top.backend.wptr_gray_sync.clk  = io_in[1];
  assign \mchip.top.backend.wptr_gray_sync.d  = { \mchip.top.frontend.wptr_reg.q [3], \mchip.top.frontend.wptr_gray [2:0], \mchip.top.backend.wptr_gray_sync.q [7:4] };
  assign \mchip.top.backend.wptr_gray_sync.en  = 1'h1;
  assign \mchip.top.backend.wptr_gray_sync.rst  = io_in[2];
  assign \mchip.top.empty  = \mchip.top.backend.empty ;
  assign \mchip.top.frontend.rptr_gray  = { \mchip.top.backend.rptr_reg.q [3], \mchip.top.backend.rptr_gray [2:0] };
  assign \mchip.top.frontend.rptr_gray1  = \mchip.top.frontend.rptr_gray_sync.q [7:4];
  assign \mchip.top.frontend.rptr_gray2  = \mchip.top.frontend.rptr_gray_sync.q [3:0];
  assign \mchip.top.frontend.rptr_gray_sync.clk  = io_in[12];
  assign \mchip.top.frontend.rptr_gray_sync.d  = { \mchip.top.backend.rptr_reg.q [3], \mchip.top.backend.rptr_gray [2:0], \mchip.top.frontend.rptr_gray_sync.q [7:4] };
  assign \mchip.top.frontend.rptr_gray_sync.en  = 1'h1;
  assign \mchip.top.frontend.rptr_gray_sync.rst  = io_in[2];
  assign \mchip.top.frontend.rst  = io_in[2];
  assign \mchip.top.frontend.wclk  = io_in[12];
  assign \mchip.top.frontend.we  = io_in[3];
  assign \mchip.top.frontend.wptr  = \mchip.top.frontend.wptr_reg.q ;
  assign \mchip.top.frontend.wptr_b2g.binary  = \mchip.top.frontend.wptr_reg.q ;
  assign \mchip.top.frontend.wptr_b2g.gray  = { \mchip.top.frontend.wptr_reg.q [3], \mchip.top.frontend.wptr_gray [2:0] };
  assign \mchip.top.frontend.wptr_gray [3] = \mchip.top.frontend.wptr_reg.q [3];
  assign \mchip.top.frontend.wptr_reg.clk  = io_in[12];
  assign \mchip.top.frontend.wptr_reg.d [1] = \mchip.top.frontend.wptr_gray [0];
  assign \mchip.top.frontend.wptr_reg.rst  = io_in[2];
  assign \mchip.top.full  = \mchip.top.frontend.full ;
  assign \mchip.top.rclk  = io_in[1];
  assign \mchip.top.rdata  = io_out[7:5];
  assign \mchip.top.re  = io_in[4];
  assign \mchip.top.rptr  = \mchip.top.backend.rptr_reg.q ;
  assign \mchip.top.rptr_gray  = { \mchip.top.backend.rptr_reg.q [3], \mchip.top.backend.rptr_gray [2:0] };
  assign \mchip.top.rst  = io_in[2];
  assign \mchip.top.wclk  = io_in[12];
  assign \mchip.top.wdata  = io_in[7:5];
  assign \mchip.top.we  = io_in[3];
  assign \mchip.top.wptr  = \mchip.top.frontend.wptr_reg.q ;
  assign \mchip.top.wptr_gray  = { \mchip.top.frontend.wptr_reg.q [3], \mchip.top.frontend.wptr_gray [2:0] };
endmodule
