/* Generated by Yosys 0.25+83 (git sha1 755b753e1, aarch64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

/* top =  1  */
/* src = "d03_example_beepboop/src/toplevel_chip.v:4.1-18.10" */
module d03_example_beepboop(io_in, io_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  /* force_downto = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:31.28-31.39|/Users/anish/workspace/oss-cad-suite/libexec/../share/yosys/techmap.v:270.26-270.27" */
  wire [15:0] _265_;
  /* src = "d03_example_beepboop/src/toplevel_chip.v:5.18-5.23" */
  input [13:0] io_in;
  wire [13:0] io_in;
  /* src = "d03_example_beepboop/src/toplevel_chip.v:6.19-6.25" */
  output [13:0] io_out;
  wire [13:0] io_out;
  /* hdlname = "mchip beepboop" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:20.19-20.27" */
  wire [0:191] \mchip.beepboop ;
  /* hdlname = "mchip btn" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:9.10-9.13" */
  wire \mchip.btn ;
  /* hdlname = "mchip chr_out" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:12.11-12.18" */
  wire \mchip.chr_out ;
  /* hdlname = "mchip chr_out_valid" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:12.20-12.33" */
  wire \mchip.chr_out_valid ;
  /* hdlname = "mchip clock" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:5.17-5.22" */
  wire \mchip.clock ;
  /* hdlname = "mchip counter" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:17.18-17.25" */
  reg [15:0] \mchip.counter ;
  /* hdlname = "mchip green" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:11.24-11.29" */
  wire \mchip.green ;
  /* hdlname = "mchip io_in" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:4.24-4.29" */
  /* unused_bits = "1 2 3 4 5 6 7 8 9 10 11" */
  wire [11:0] \mchip.io_in ;
  /* hdlname = "mchip io_out" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:6.25-6.31" */
  wire [11:0] \mchip.io_out ;
  /* hdlname = "mchip no_walk" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:11.37-11.44" */
  wire \mchip.no_walk ;
  /* hdlname = "mchip red" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:11.11-11.14" */
  wire \mchip.red ;
  /* hdlname = "mchip reset" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:5.24-5.29" */
  wire \mchip.reset ;
  /* hdlname = "mchip the_beepbooper" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:11.46-11.60" */
  wire \mchip.the_beepbooper ;
  /* hdlname = "mchip walk" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:11.31-11.35" */
  wire \mchip.walk ;
  /* hdlname = "mchip yellow" */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:11.16-11.22" */
  wire \mchip.yellow ;
  assign _215_ = ~(\mchip.counter [15] | \mchip.counter [14]);
  assign _216_ = \mchip.counter [12] | \mchip.counter [13];
  assign _217_ = _215_ & ~(_216_);
  assign _218_ = \mchip.counter [10] | \mchip.counter [11];
  assign _219_ = ~(\mchip.counter [8] | \mchip.counter [9]);
  assign _220_ = _219_ & ~(_218_);
  assign _221_ = ~(_220_ & _217_);
  assign _222_ = \mchip.counter [6] | \mchip.counter [7];
  assign _223_ = \mchip.counter [4] | \mchip.counter [5];
  assign _116_ = ~(_223_ | _222_);
  assign _224_ = ~(\mchip.counter [2] | \mchip.counter [3]);
  assign _225_ = \mchip.counter [0] | \mchip.counter [1];
  assign _108_ = _224_ & ~(_225_);
  assign _226_ = ~(_108_ & _116_);
  assign _002_ = _226_ | _221_;
  assign _227_ = io_in[0] & ~(_002_);
  assign _228_ = \mchip.counter [11] & ~(\mchip.counter [10]);
  assign _229_ = ~(_228_ & _219_);
  assign _230_ = _217_ & ~(_229_);
  assign _231_ = \mchip.counter [2] | ~(\mchip.counter [3]);
  assign _232_ = _231_ | _225_;
  assign _233_ = \mchip.counter [6] | ~(\mchip.counter [7]);
  assign _234_ = \mchip.counter [5] | ~(\mchip.counter [4]);
  assign _235_ = ~(_234_ | _233_);
  assign _236_ = _232_ | ~(_235_);
  assign _237_ = _230_ & ~(_236_);
  assign _238_ = _237_ | _227_;
  assign _239_ = \mchip.counter [11] | ~(_217_);
  assign _240_ = ~(_233_ | _223_);
  assign _241_ = \mchip.counter [7] & ~(_240_);
  assign _242_ = _232_ & \mchip.counter [3];
  assign _243_ = _235_ & ~(_242_);
  assign _244_ = _241_ & ~(_243_);
  assign _245_ = _230_ & ~(_244_);
  assign _246_ = _239_ & ~(_245_);
  assign _247_ = _246_ | io_in[13];
  assign _001_ = _247_ | _238_;
  assign _248_ = _246_ | _237_;
  assign _249_ = _248_ | _227_;
  assign _000_ = _249_ | _002_;
  assign _250_ = \mchip.counter [9] | ~(\mchip.counter [8]);
  assign _251_ = _250_ | _218_;
  assign _252_ = _217_ & ~(_251_);
  assign _253_ = _222_ | \mchip.counter [5];
  assign _254_ = \mchip.counter [4] | ~(\mchip.counter [5]);
  assign _255_ = ~(_254_ | _222_);
  assign _256_ = ~(\mchip.counter [2] & \mchip.counter [3]);
  assign _257_ = _225_ & ~(_256_);
  assign _258_ = _255_ & ~(_257_);
  assign _259_ = _253_ & ~(_258_);
  assign _260_ = _252_ & ~(_259_);
  assign _261_ = _221_ & ~(_260_);
  assign _262_ = _256_ | _225_;
  assign _263_ = _262_ | ~(_255_);
  assign _264_ = _263_ | ~(_252_);
  assign _004_ = ~(_264_ & _261_);
  assign _005_ = \mchip.counter [4] & \mchip.counter [5];
  assign _006_ = _005_ & ~(_222_);
  assign _007_ = \mchip.counter [3] | ~(\mchip.counter [2]);
  assign _008_ = ~(_007_ | _225_);
  assign _009_ = ~(_008_ & _006_);
  assign _010_ = _230_ & ~(_009_);
  assign _011_ = _005_ | _222_;
  assign _012_ = \mchip.counter [2] | \mchip.counter [3];
  assign _013_ = _012_ & ~(_008_);
  assign _014_ = _006_ & ~(_013_);
  assign _015_ = _011_ & ~(_014_);
  assign _016_ = _230_ & ~(_015_);
  assign _017_ = _239_ & ~(_016_);
  assign _018_ = _017_ | _010_;
  assign _019_ = ~(\mchip.counter [8] & \mchip.counter [9]);
  assign _020_ = \mchip.counter [11] | ~(\mchip.counter [10]);
  assign _021_ = _020_ | _019_;
  assign _022_ = _217_ & ~(_021_);
  assign _023_ = \mchip.counter [7] | ~(\mchip.counter [6]);
  assign _024_ = _023_ | _254_;
  assign _025_ = _024_ | _262_;
  assign _026_ = _022_ & ~(_025_);
  assign _027_ = ~_217_;
  assign _028_ = _019_ & ~(_020_);
  assign _029_ = _218_ & ~(_028_);
  assign _030_ = _029_ | _027_;
  assign _031_ = ~\mchip.counter [5];
  assign _032_ = _031_ & ~(_023_);
  assign _033_ = _222_ & ~(_032_);
  assign _034_ = ~(_024_ | _257_);
  assign _035_ = _033_ & ~(_034_);
  assign _036_ = _022_ & ~(_035_);
  assign _037_ = _030_ & ~(_036_);
  assign _038_ = _037_ | _026_;
  assign _039_ = \mchip.counter [6] & \mchip.counter [7];
  assign _040_ = _234_ | ~(_039_);
  assign _041_ = _040_ | ~(_108_);
  assign _042_ = _022_ & ~(_041_);
  assign _043_ = ~(\mchip.counter [4] | \mchip.counter [5]);
  assign _044_ = _039_ & ~(_043_);
  assign _045_ = _044_ & _041_;
  assign _046_ = _022_ & ~(_045_);
  assign _047_ = _030_ & ~(_046_);
  assign _048_ = _047_ | _042_;
  assign _049_ = _038_ & ~(_048_);
  assign _050_ = \mchip.counter [8] | ~(\mchip.counter [9]);
  assign _051_ = _050_ | _020_;
  assign _052_ = _217_ & ~(_051_);
  assign _053_ = _254_ | _233_;
  assign _054_ = _053_ | ~(_008_);
  assign _055_ = _052_ & ~(_054_);
  assign _056_ = ~(_020_ | \mchip.counter [9]);
  assign _057_ = _218_ & ~(_056_);
  assign _058_ = _057_ | _027_;
  assign _059_ = _031_ & ~(_233_);
  assign _060_ = \mchip.counter [7] & ~(_059_);
  assign _061_ = ~(_053_ | _013_);
  assign _062_ = _060_ & ~(_061_);
  assign _063_ = _052_ & ~(_062_);
  assign _064_ = _058_ & ~(_063_);
  assign _065_ = _064_ | _055_;
  assign _066_ = _232_ | ~(_116_);
  assign _067_ = _022_ & ~(_066_);
  assign _068_ = _242_ | ~(_116_);
  assign _069_ = _022_ & ~(_068_);
  assign _070_ = _030_ & ~(_069_);
  assign _071_ = _070_ | _067_;
  assign _072_ = _065_ & ~(_071_);
  assign _073_ = _023_ | _223_;
  assign _074_ = _108_ & ~(_073_);
  assign _075_ = ~(_074_ & _052_);
  assign _076_ = _222_ & ~(_074_);
  assign _077_ = _052_ & ~(_076_);
  assign _078_ = _058_ & ~(_077_);
  assign _079_ = _075_ & ~(_078_);
  assign _080_ = ~(_020_ | _250_);
  assign _081_ = ~(_080_ & _217_);
  assign _082_ = _040_ | _262_;
  assign _083_ = ~(_082_ | _081_);
  assign _084_ = ~(_040_ | _257_);
  assign _085_ = _044_ & ~(_084_);
  assign _086_ = _085_ | _081_;
  assign _087_ = _219_ & ~(_020_);
  assign _088_ = _218_ & ~(_087_);
  assign _089_ = _217_ & ~(_088_);
  assign _090_ = _086_ & ~(_089_);
  assign _091_ = ~(_090_ | _083_);
  assign _092_ = _079_ & ~(_091_);
  assign _093_ = _092_ | _072_;
  assign _094_ = _093_ | _049_;
  assign _095_ = _094_ | _018_;
  assign \mchip.no_walk  = _095_ | _004_;
  assign \mchip.the_beepbooper  = _091_ & _261_;
  assign _096_ = ~(_039_ & _043_);
  assign _097_ = _096_ | _232_;
  assign _098_ = ~(_097_ | _221_);
  assign _099_ = ~(_096_ | _242_);
  assign _100_ = _039_ & ~(_099_);
  assign _101_ = _100_ | _221_;
  assign _102_ = _101_ | _098_;
  assign \mchip.red  = _102_ & ~(_248_);
  assign \mchip.yellow  = _002_ & ~(_102_);
  assign \mchip.green  = _248_ | ~(_002_);
  assign _103_ = _108_ & ~(_096_);
  assign _104_ = _221_ | ~(_103_);
  assign _105_ = _039_ & ~(_103_);
  assign _106_ = ~(_105_ | _221_);
  assign _107_ = _104_ & ~(_106_);
  assign \mchip.chr_out_valid  = _002_ & ~(_107_);
  assign _109_ = _108_ & ~(_223_);
  assign _110_ = _109_ ^ \mchip.counter [6];
  assign _111_ = ~_110_;
  assign _112_ = \mchip.counter [0] & \mchip.counter [1];
  assign _113_ = _225_ & ~(_112_);
  assign _114_ = ~\mchip.counter [0];
  assign _115_ = ~\mchip.counter [8];
  assign _117_ = _116_ & ~(_108_);
  assign _118_ = _117_ | ~(_116_);
  assign _119_ = _118_ ^ _115_;
  assign _120_ = _109_ & ~(\mchip.counter [6]);
  assign _121_ = ~(_120_ ^ \mchip.counter [7]);
  assign _122_ = _110_ & ~(_121_);
  assign _123_ = _122_ | _119_;
  assign _124_ = _115_ & ~(_118_);
  assign _125_ = _124_ ^ \mchip.counter [9];
  assign _126_ = _125_ ^ _123_;
  assign _127_ = _126_ | _114_;
  assign _128_ = _114_ & ~(_126_);
  assign _129_ = _127_ & ~(_128_);
  assign _130_ = _113_ & ~(_129_);
  assign _131_ = ~_113_;
  assign _132_ = _131_ & ~(_129_);
  assign _133_ = ~(_132_ | _130_);
  assign _134_ = ~\mchip.counter [2];
  assign _135_ = _225_ ^ _134_;
  assign _136_ = _126_ | \mchip.counter [0];
  assign _137_ = _113_ ? _136_ : _127_;
  assign _138_ = _134_ & ~(_225_);
  assign _139_ = _138_ ^ \mchip.counter [3];
  assign _140_ = _135_ ? _133_ : _137_;
  assign _141_ = _108_ ^ \mchip.counter [4];
  assign _142_ = ~_135_;
  assign _143_ = _136_ | _131_;
  assign _144_ = _127_ | _113_;
  assign _145_ = _135_ ? _144_ : _143_;
  assign _146_ = _144_ | _135_;
  assign _147_ = _139_ ? _145_ : _146_;
  assign _148_ = _141_ ? _140_ : _147_;
  assign _149_ = _108_ & ~(\mchip.counter [4]);
  assign _150_ = _149_ ^ \mchip.counter [5];
  assign _151_ = _113_ ? _136_ : _129_;
  assign _152_ = _151_ | _135_;
  assign _153_ = _135_ ? _136_ : _137_;
  assign _154_ = _139_ ? _152_ : _153_;
  assign _155_ = _139_ ? _153_ : _145_;
  assign _156_ = _141_ ? _154_ : _155_;
  assign _157_ = _150_ ? _148_ : _156_;
  assign _158_ = _111_ & ~(_157_);
  assign _159_ = _121_ ^ _110_;
  assign _160_ = _135_ ? _143_ : _151_;
  assign _161_ = ~(_160_ | _139_);
  assign _162_ = \mchip.counter [0] & ~(_126_);
  assign _163_ = _113_ ? _128_ : _162_;
  assign _164_ = _113_ & ~(_127_);
  assign _165_ = _135_ ? _164_ : _163_;
  assign _166_ = ~(_136_ & _127_);
  assign _167_ = _113_ ? _128_ : _166_;
  assign _168_ = _135_ ? _167_ : _163_;
  assign _169_ = _139_ ? _165_ : _168_;
  assign _170_ = _141_ ? _161_ : _169_;
  assign _171_ = _113_ ? _162_ : _128_;
  assign _172_ = _135_ ? _171_ : _163_;
  assign _173_ = _113_ & ~(_136_);
  assign _174_ = _135_ ? _130_ : _173_;
  assign _175_ = _139_ ? _172_ : _174_;
  assign _176_ = _142_ & ~(_144_);
  assign _177_ = _135_ ? _132_ : _163_;
  assign _178_ = _139_ ? _176_ : _177_;
  assign _179_ = _141_ ? _175_ : _178_;
  assign _180_ = _150_ ? _170_ : _179_;
  assign _181_ = _139_ ? _172_ : _163_;
  assign _182_ = _131_ & ~(_136_);
  assign _183_ = _135_ ? _182_ : _163_;
  assign _184_ = _139_ ? _163_ : _183_;
  assign _185_ = _141_ ? _181_ : _184_;
  assign _186_ = _131_ & ~(_127_);
  assign _187_ = _135_ ? _186_ : _167_;
  assign _188_ = _135_ ? _173_ : _128_;
  assign _189_ = _139_ ? _187_ : _188_;
  assign _190_ = _142_ & ~(_151_);
  assign _191_ = _139_ ? _176_ : _190_;
  assign _192_ = _141_ ? _189_ : _191_;
  assign _193_ = _150_ ? _185_ : _192_;
  assign _194_ = _110_ ? _193_ : _180_;
  assign _195_ = _159_ ? _158_ : _194_;
  assign _196_ = _122_ ^ _119_;
  assign \mchip.chr_out  = _195_ & ~(_196_);
  assign _265_[1] = \mchip.counter [0] ^ \mchip.counter [1];
  assign _265_[2] = _112_ ^ \mchip.counter [2];
  assign _197_ = _112_ & ~(_134_);
  assign _265_[3] = _197_ ^ \mchip.counter [3];
  assign _198_ = _112_ & ~(_256_);
  assign _265_[4] = _198_ ^ \mchip.counter [4];
  assign _199_ = _198_ & \mchip.counter [4];
  assign _265_[5] = _199_ ^ \mchip.counter [5];
  assign _200_ = _198_ & _005_;
  assign _265_[6] = _200_ ^ \mchip.counter [6];
  assign _201_ = _200_ & \mchip.counter [6];
  assign _265_[7] = _201_ ^ \mchip.counter [7];
  assign _202_ = _039_ & _005_;
  assign _203_ = ~(_202_ & _198_);
  assign _265_[8] = _203_ ^ _115_;
  assign _204_ = \mchip.counter [8] & ~(_203_);
  assign _265_[9] = _204_ ^ \mchip.counter [9];
  assign _205_ = ~(_203_ | _019_);
  assign _265_[10] = _205_ ^ \mchip.counter [10];
  assign _206_ = _205_ & \mchip.counter [10];
  assign _265_[11] = _206_ ^ \mchip.counter [11];
  assign _207_ = ~(\mchip.counter [10] & \mchip.counter [11]);
  assign _208_ = _207_ | _019_;
  assign _209_ = ~(_208_ | _203_);
  assign _265_[12] = _209_ ^ \mchip.counter [12];
  assign _210_ = _209_ & \mchip.counter [12];
  assign _265_[13] = _210_ ^ \mchip.counter [13];
  assign _211_ = ~(\mchip.counter [12] & \mchip.counter [13]);
  assign _212_ = _209_ & ~(_211_);
  assign _265_[14] = _212_ ^ \mchip.counter [14];
  assign _213_ = _212_ & \mchip.counter [14];
  assign _265_[15] = _213_ ^ \mchip.counter [15];
  assign _214_ = _114_ & ~(_248_);
  assign _003_ = _214_ | _227_;
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (io_in[13]) \mchip.counter [0] <= 1'h0;
    else if (_000_) \mchip.counter [0] <= _003_;
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [1] <= 1'h0;
    else if (_002_) \mchip.counter [1] <= _265_[1];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [2] <= 1'h0;
    else if (_002_) \mchip.counter [2] <= _265_[2];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [3] <= 1'h0;
    else if (_002_) \mchip.counter [3] <= _265_[3];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [4] <= 1'h0;
    else if (_002_) \mchip.counter [4] <= _265_[4];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [5] <= 1'h0;
    else if (_002_) \mchip.counter [5] <= _265_[5];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [6] <= 1'h0;
    else if (_002_) \mchip.counter [6] <= _265_[6];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [7] <= 1'h0;
    else if (_002_) \mchip.counter [7] <= _265_[7];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [8] <= 1'h0;
    else if (_002_) \mchip.counter [8] <= _265_[8];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [9] <= 1'h0;
    else if (_002_) \mchip.counter [9] <= _265_[9];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [10] <= 1'h0;
    else if (_002_) \mchip.counter [10] <= _265_[10];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [11] <= 1'h0;
    else if (_002_) \mchip.counter [11] <= _265_[11];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [12] <= 1'h0;
    else if (_002_) \mchip.counter [12] <= _265_[12];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [13] <= 1'h0;
    else if (_002_) \mchip.counter [13] <= _265_[13];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [14] <= 1'h0;
    else if (_002_) \mchip.counter [14] <= _265_[14];
  /* \always_ff  = 32'd1 */
  /* src = "d03_example_beepboop/src/toplevel_chip.v:9.13-14.6|d03_example_beepboop/src/chip.sv:25.5-42.8" */
  always @(posedge io_in[12])
    if (_001_) \mchip.counter [15] <= 1'h0;
    else if (_002_) \mchip.counter [15] <= _265_[15];
  assign _265_[0] = 1'h0;
  assign io_out = { 6'h00, \mchip.chr_out_valid , \mchip.chr_out , \mchip.the_beepbooper , \mchip.no_walk , \mchip.the_beepbooper , \mchip.green , \mchip.yellow , \mchip.red  };
  assign \mchip.beepboop  = 192'h4265657020426f6f702054726166666963204c6967687400;
  assign \mchip.btn  = io_in[0];
  assign \mchip.clock  = io_in[12];
  assign \mchip.io_in  = io_in[11:0];
  assign \mchip.io_out  = { 4'h0, \mchip.chr_out_valid , \mchip.chr_out , \mchip.the_beepbooper , \mchip.no_walk , \mchip.the_beepbooper , \mchip.green , \mchip.yellow , \mchip.red  };
  assign \mchip.reset  = io_in[13];
  assign \mchip.walk  = \mchip.the_beepbooper ;
endmodule
